import type { CitationType } from "../types";

export type Citation = {
  id: string;
  title: string;
  authors: string;
  year: number;
  source: string;
  url: string;
  type: CitationType;
  pmid?: string;
};

export const CITATIONS: Record<string, Citation> = {
  nice_ng59: {
    id: "nice_ng59",
    title: "Low back pain and sciatica in over 16s: assessment and management",
    authors: "National Institute for Health and Care Excellence",
    year: 2020,
    source: "NICE Guideline NG59",
    url: "https://www.nice.org.uk/guidance/ng59",
    type: "guia",
  },
  chou_2007: {
    id: "chou_2007",
    title:
      "Diagnosis and treatment of low back pain: a joint clinical practice guideline",
    authors: "Chou R, Qaseem A, Snow V, et al.",
    year: 2007,
    source: "Ann Intern Med",
    url: "https://pubmed.ncbi.nlm.nih.gov/17909209/",
    type: "guia",
    pmid: "17909209",
  },
  nass_lumbar_radic: {
    id: "nass_lumbar_radic",
    title:
      "An evidence-based clinical guideline for the diagnosis and treatment of lumbar disc herniation with radiculopathy",
    authors: "Kreiner DS, Hwang SW, Easa JE, et al. (NASS)",
    year: 2014,
    source: "Spine J",
    url: "https://pubmed.ncbi.nlm.nih.gov/24239490/",
    type: "guia",
    pmid: "24239490",
  },
  deyo_2016: {
    id: "deyo_2016",
    title: "Herniated lumbar intervertebral disk",
    authors: "Deyo RA, Mirza SK",
    year: 2016,
    source: "N Engl J Med",
    url: "https://pubmed.ncbi.nlm.nih.gov/27028912/",
    type: "revision",
    pmid: "27028912",
  },
  nass_stenosis: {
    id: "nass_stenosis",
    title:
      "An evidence-based clinical guideline for the diagnosis and treatment of degenerative lumbar spinal stenosis",
    authors: "Kreiner DS, Shaffer WO, Baisden JL, et al. (NASS)",
    year: 2013,
    source: "Spine J",
    url: "https://pubmed.ncbi.nlm.nih.gov/23497946/",
    type: "guia",
    pmid: "23497946",
  },
  jospt_neck_2017: {
    id: "jospt_neck_2017",
    title: "Neck Pain: Revision 2017. Clinical Practice Guidelines",
    authors: "Blanpied PR, Gross AR, Elliott JM, et al.",
    year: 2017,
    source: "J Orthop Sports Phys Ther",
    url: "https://pubmed.ncbi.nlm.nih.gov/28666405/",
    type: "guia",
    pmid: "28666405",
  },
  nass_cervical_radic: {
    id: "nass_cervical_radic",
    title:
      "An evidence-based clinical guideline for the diagnosis and treatment of cervical radiculopathy from degenerative disorders",
    authors: "Bono CM, Ghiselli G, Gilbert TJ, et al. (NASS)",
    year: 2011,
    source: "Spine J",
    url: "https://pubmed.ncbi.nlm.nih.gov/21168100/",
    type: "guia",
    pmid: "21168100",
  },
  fehlings_2017: {
    id: "fehlings_2017",
    title:
      "A clinical practice guideline for the management of degenerative cervical myelopathy",
    authors: "Fehlings MG, Tetreault LA, Riew KD, et al.",
    year: 2017,
    source: "Global Spine J",
    url: "https://pubmed.ncbi.nlm.nih.gov/29164035/",
    type: "guia",
    pmid: "29164035",
  },
  jospt_shoulder_2020: {
    id: "jospt_shoulder_2020",
    title: "Shoulder Pain and Mobility Deficits: Adhesive Capsulitis",
    authors: "Kelley MJ, Shaffer MA, Kuhn JE, et al.",
    year: 2013,
    source: "J Orthop Sports Phys Ther",
    url: "https://pubmed.ncbi.nlm.nih.gov/23636125/",
    type: "guia",
    pmid: "23636125",
  },
  aaos_rc: {
    id: "aaos_rc",
    title: "Management of Rotator Cuff Injuries. Clinical Practice Guideline",
    authors: "American Academy of Orthopaedic Surgeons",
    year: 2019,
    source: "AAOS CPG",
    url: "https://www.aaos.org/quality/quality-programs/upper-extremity-programs/rotator-cuff-injuries/",
    type: "guia",
  },
  kuhn_2009: {
    id: "kuhn_2009",
    title: "Exercise in the treatment of rotator cuff impingement: a systematic review",
    authors: "Kuhn JE",
    year: 2009,
    source: "J Shoulder Elbow Surg",
    url: "https://pubmed.ncbi.nlm.nih.gov/19101175/",
    type: "revision",
    pmid: "19101175",
  },
  coombes_2015: {
    id: "coombes_2015",
    title: "Management of lateral elbow tendinopathy: one size does not fit all",
    authors: "Coombes BK, Bisset L, Vicenzino B",
    year: 2015,
    source: "J Orthop Sports Phys Ther",
    url: "https://pubmed.ncbi.nlm.nih.gov/26381484/",
    type: "revision",
    pmid: "26381484",
  },
  padua_2016: {
    id: "padua_2016",
    title: "Carpal tunnel syndrome: clinical features, diagnosis, and management",
    authors: "Padua L, Coraci D, Erra C, et al.",
    year: 2016,
    source: "Lancet Neurol",
    url: "https://pubmed.ncbi.nlm.nih.gov/27571119/",
    type: "revision",
    pmid: "27571119",
  },
  oarsi_2019: {
    id: "oarsi_2019",
    title:
      "OARSI guidelines for the non-surgical management of knee, hip, and polyarticular osteoarthritis",
    authors: "Bannuru RR, Osani MC, Vaysbrot EE, et al.",
    year: 2019,
    source: "Osteoarthritis Cartilage",
    url: "https://pubmed.ncbi.nlm.nih.gov/31278991/",
    type: "guia",
    pmid: "31278991",
  },
  acr_oa_2020: {
    id: "acr_oa_2020",
    title:
      "2019 American College of Rheumatology/Arthritis Foundation Guideline for the Management of Osteoarthritis of the Hand, Hip, and Knee",
    authors: "Kolasinski SL, Neogi T, Hochberg MC, et al.",
    year: 2020,
    source: "Arthritis Care Res",
    url: "https://pubmed.ncbi.nlm.nih.gov/31908163/",
    type: "guia",
    pmid: "31908163",
  },
  jospt_pfps: {
    id: "jospt_pfps",
    title: "Patellofemoral Pain. Clinical Practice Guidelines",
    authors: "Willy RW, Hoglund LT, Barton CJ, et al.",
    year: 2019,
    source: "J Orthop Sports Phys Ther",
    url: "https://pubmed.ncbi.nlm.nih.gov/31475628/",
    type: "guia",
    pmid: "31475628",
  },
  jospt_hip_oa: {
    id: "jospt_hip_oa",
    title: "Hip Pain and Mobility Deficits — Hip Osteoarthritis: Revision 2017",
    authors: "Cibulka MT, Bloom NJ, Enseki KR, et al.",
    year: 2017,
    source: "J Orthop Sports Phys Ther",
    url: "https://pubmed.ncbi.nlm.nih.gov/28566053/",
    type: "guia",
    pmid: "28566053",
  },
  vuurberg_2018: {
    id: "vuurberg_2018",
    title:
      "Diagnosis, treatment and prevention of ankle sprains: update of an evidence-based clinical guideline",
    authors: "Vuurberg G, Hoorntje A, Wink LM, et al.",
    year: 2018,
    source: "Br J Sports Med",
    url: "https://pubmed.ncbi.nlm.nih.gov/29514819/",
    type: "guia",
    pmid: "29514819",
  },
  jospt_plantar: {
    id: "jospt_plantar",
    title: "Heel Pain — Plantar Fasciitis: Revision 2014",
    authors: "Martin RL, Davenport TE, Reischl SF, et al.",
    year: 2014,
    source: "J Orthop Sports Phys Ther",
    url: "https://pubmed.ncbi.nlm.nih.gov/25173178/",
    type: "guia",
    pmid: "25173178",
  },
  jospt_achilles: {
    id: "jospt_achilles",
    title: "Achilles Pain, Stiffness, and Muscle Power Deficits: Midportion Achilles Tendinopathy Revision 2018",
    authors: "Martin RL, Chimenti R, Cuddeford T, et al.",
    year: 2018,
    source: "J Orthop Sports Phys Ther",
    url: "https://pubmed.ncbi.nlm.nih.gov/29712543/",
    type: "guia",
    pmid: "29712543",
  },
  nice_ng71: {
    id: "nice_ng71",
    title: "Parkinson’s disease in adults",
    authors: "National Institute for Health and Care Excellence",
    year: 2017,
    source: "NICE Guideline NG71",
    url: "https://www.nice.org.uk/guidance/ng71",
    type: "guia",
  },
  keus_kngf: {
    id: "keus_kngf",
    title: "European Physiotherapy Guideline for Parkinson’s Disease",
    authors: "Keus SHJ, Munneke M, Graziano M, et al.",
    year: 2014,
    source: "KNGF / ParkinsonNet",
    url: "https://www.parkinsonnet.com/guidelines/",
    type: "guia",
  },
  aha_stroke_2016: {
    id: "aha_stroke_2016",
    title:
      "Guidelines for Adult Stroke Rehabilitation and Recovery: A Guideline for Healthcare Professionals",
    authors: "Winstein CJ, Stein J, Arena R, et al. (AHA/ASA)",
    year: 2016,
    source: "Stroke",
    url: "https://pubmed.ncbi.nlm.nih.gov/27145936/",
    type: "guia",
    pmid: "27145936",
  },
  nice_ng220: {
    id: "nice_ng220",
    title: "Multiple sclerosis in adults: management",
    authors: "National Institute for Health and Care Excellence",
    year: 2022,
    source: "NICE Guideline NG220",
    url: "https://www.nice.org.uk/guidance/ng220",
    type: "guia",
  },
  popbusui_2017: {
    id: "popbusui_2017",
    title: "Diabetic Neuropathy: A Position Statement by the American Diabetes Association",
    authors: "Pop-Busui R, Boulton AJM, Feldman EL, et al.",
    year: 2017,
    source: "Diabetes Care",
    url: "https://pubmed.ncbi.nlm.nih.gov/27999003/",
    type: "consenso",
    pmid: "27999003",
  },
  nice_cg161: {
    id: "nice_cg161",
    title: "Falls in older people: assessing risk and prevention",
    authors: "National Institute for Health and Care Excellence",
    year: 2013,
    source: "NICE Clinical Guideline CG161",
    url: "https://www.nice.org.uk/guidance/cg161",
    type: "guia",
  },
  ags_bgs_falls: {
    id: "ags_bgs_falls",
    title:
      "Summary of the Updated American Geriatrics Society/British Geriatrics Society clinical practice guideline for prevention of falls in older persons",
    authors: "AGS/BGS Panel",
    year: 2011,
    source: "J Am Geriatr Soc",
    url: "https://pubmed.ncbi.nlm.nih.gov/21226685/",
    type: "guia",
    pmid: "21226685",
  },
  bhattacharyya_2017: {
    id: "bhattacharyya_2017",
    title:
      "Clinical Practice Guideline: Benign Paroxysmal Positional Vertigo (Update)",
    authors: "Bhattacharyya N, Gubbels SP, Schwartz SR, et al.",
    year: 2017,
    source: "Otolaryngol Head Neck Surg",
    url: "https://pubmed.ncbi.nlm.nih.gov/28248609/",
    type: "guia",
    pmid: "28248609",
  },
  eular_fm_2017: {
    id: "eular_fm_2017",
    title: "EULAR revised recommendations for the management of fibromyalgia",
    authors: "Macfarlane GJ, Kronisch C, Dean LE, et al.",
    year: 2017,
    source: "Ann Rheum Dis",
    url: "https://pubmed.ncbi.nlm.nih.gov/27377815/",
    type: "guia",
    pmid: "27377815",
  },
  nice_ng65: {
    id: "nice_ng65",
    title: "Spondyloarthritis in over 16s: diagnosis and management",
    authors: "National Institute for Health and Care Excellence",
    year: 2017,
    source: "NICE Guideline NG65",
    url: "https://www.nice.org.uk/guidance/ng65",
    type: "guia",
  },
  todd_cauda: {
    id: "todd_cauda",
    title:
      "Guidelines for cauda equina syndrome. Red flags and yellow flags",
    authors: "Todd NV",
    year: 2017,
    source: "Br J Neurosurg",
    url: "https://pubmed.ncbi.nlm.nih.gov/28539079/",
    type: "revision",
    pmid: "28539079",
  },
  nice_ng158: {
    id: "nice_ng158",
    title: "Venous thromboembolic diseases: diagnosis, management and thrombophilia testing",
    authors: "National Institute for Health and Care Excellence",
    year: 2020,
    source: "NICE Guideline NG158",
    url: "https://www.nice.org.uk/guidance/ng158",
    type: "guia",
  },
  wells_2003: {
    id: "wells_2003",
    title: "Evaluation of D-dimer in the diagnosis of suspected deep-vein thrombosis",
    authors: "Wells PS, Anderson DR, Rodger M, et al.",
    year: 2003,
    source: "N Engl J Med",
    url: "https://pubmed.ncbi.nlm.nih.gov/12968035/",
    type: "ensayo",
    pmid: "12968035",
  },
  willison_gbs: {
    id: "willison_gbs",
    title: "Guillain-Barré syndrome",
    authors: "Willison HJ, Jacobs BC, van Doorn PA",
    year: 2016,
    source: "Lancet",
    url: "https://pubmed.ncbi.nlm.nih.gov/26948435/",
    type: "revision",
    pmid: "26948435",
  },
  daniels_worthingham: {
    id: "daniels_worthingham",
    title: "Daniels and Worthingham's Muscle Testing",
    authors: "Avers D, Brown M",
    year: 2018,
    source: "Elsevier (10th ed.)",
    url: "https://www.elsevier.com/books/daniels-and-worthinghams-muscle-testing/avers/978-0-323-56956-9",
    type: "consenso",
  },
  campbell_reflexes: {
    id: "campbell_reflexes",
    title: "DeJong's The Neurologic Examination",
    authors: "Campbell WW",
    year: 2012,
    source: "Lippincott Williams & Wilkins",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    type: "consenso",
  },
  hjermstad_vas: {
    id: "hjermstad_vas",
    title:
      "Studies comparing Numerical Rating Scales, Verbal Rating Scales, and Visual Analogue Scales for assessment of pain intensity in adults: a systematic literature review",
    authors: "Hjermstad MJ, Fayers PM, Haugen DF, et al.",
    year: 2011,
    source: "J Pain Symptom Manage",
    url: "https://pubmed.ncbi.nlm.nih.gov/21621130/",
    type: "revision",
    pmid: "21621130",
  },
  berg_1989: {
    id: "berg_1989",
    title: "Measuring balance in the elderly: preliminary development of an instrument",
    authors: "Berg K, Wood-Dauphinee S, Williams JI, Gayton D",
    year: 1989,
    source: "Physiother Can",
    url: "https://doi.org/10.3138/ptc.41.6.304",
    type: "ensayo",
  },
  podsiadlo_tug: {
    id: "podsiadlo_tug",
    title: "The Timed “Up & Go”: a test of basic functional mobility for frail elderly persons",
    authors: "Podsiadlo D, Richardson S",
    year: 1991,
    source: "J Am Geriatr Soc",
    url: "https://pubmed.ncbi.nlm.nih.gov/1991946/",
    type: "ensayo",
    pmid: "1991946",
  },
  guralnik_sppb: {
    id: "guralnik_sppb",
    title:
      "A short physical performance battery assessing lower extremity function: association with self-reported disability and prediction of mortality and nursing home admission",
    authors: "Guralnik JM, Simonsick EM, Ferrucci L, et al.",
    year: 1994,
    source: "J Gerontol",
    url: "https://pubmed.ncbi.nlm.nih.gov/8126356/",
    type: "ensayo",
    pmid: "8126356",
  },
  mahoney_barthel: {
    id: "mahoney_barthel",
    title: "Functional evaluation: the Barthel Index",
    authors: "Mahoney FI, Barthel DW",
    year: 1965,
    source: "Md State Med J",
    url: "https://pubmed.ncbi.nlm.nih.gov/14258950/",
    type: "ensayo",
    pmid: "14258950",
  },
  tinetti_1986: {
    id: "tinetti_1986",
    title: "Performance-oriented assessment of mobility problems in elderly patients",
    authors: "Tinetti ME",
    year: 1986,
    source: "J Am Geriatr Soc",
    url: "https://pubmed.ncbi.nlm.nih.gov/3944402/",
    type: "ensayo",
    pmid: "3944402",
  },
  downs_ottawa: {
    id: "downs_ottawa",
    title:
      "Accuracy of Ottawa Ankle Rules to exclude fractures of the ankle and mid-foot: systematic review",
    authors: "Bachmann LM, Kolb E, Koller MT, Steurer J, ter Riet G",
    year: 2003,
    source: "BMJ",
    url: "https://pubmed.ncbi.nlm.nih.gov/12560462/",
    type: "revision",
    pmid: "12560462",
  },
};

export function citationList(ids: string[]) {
  return ids.map((id) => CITATIONS[id]).filter(Boolean);
}

export function formatCitation(c: Citation) {
  const pmid = c.pmid ? ` PMID ${c.pmid}.` : "";
  return `${c.authors} (${c.year}). ${c.title}. ${c.source}.${pmid}`;
}
