import type { Region } from "../types";

export type AgeHint = "adulto" | "mayor" | "cualquier";

export type DiagnosisCategory =
  | "musculoesqueletico"
  | "neurologico"
  | "geriatrico"
  | "urgente";

export type Diagnosis = {
  id: string;
  name: string;
  icd10?: string;
  category: DiagnosisCategory;
  regions: Region[];
  ageHint: AgeHint;
  keywords: string[];
  signs: { text: string; weight: number }[];
  symptoms: { text: string; weight: number }[];
  rulingIn: string[];
  rulingOut: string[];
  suggestedTests: string[];
  citationIds: string[];
  treatment: {
    sessions: number;
    frequency: string;
    durationMin: number;
    agents: string[];
    exerciseIds: string[];
    education: string;
    precautions: string;
  };
  objectives: string[];
  expectedPattern: string[];
};

export const DIAGNOSES: Diagnosis[] = [
  {
    id: "lumbalgia_inespecifica",
    name: "Dolor lumbar inespecífico (lumbalgia mecánica)",
    icd10: "M54.5",
    category: "musculoesqueletico",
    regions: ["lumbar"],
    ageHint: "cualquier",
    keywords: [
      "lumbalgia", "lumbago", "dolor lumbar", "dolor de espalda baja",
      "mecánico", "axial", "rigidez matutina breve",
    ],
    signs: [
      { text: "dolor axial lumbar", weight: 3 },
      { text: "dolor mecánico que varía con postura y movimiento", weight: 3 },
      { text: "Lasègue negativo", weight: 2 },
      { text: "reflejos conservados", weight: 1 },
    ],
    symptoms: [
      { text: "dolor lumbar sin irradiación por debajo de la rodilla", weight: 3 },
      { text: "empeora al estar sentado o al flexionar", weight: 2 },
      { text: "mejora con el movimiento", weight: 2 },
      { text: "rigidez matutina menor de 30 minutos", weight: 1 },
    ],
    rulingIn: [
      "Dolor lumbar mecánico sin déficit neurológico",
      "Sin irradiación verdadera por debajo de la rodilla",
      "Lasègue negativo",
    ],
    rulingOut: [
      "Dolor irradiado con distribución dermatomérica",
      "Pérdida de fuerza o reflejos",
      "Fiebre, pérdida de peso, antecedente oncológico (banderas rojas)",
    ],
    suggestedTests: ["vas", "lasegue", "slump", "schober", "daniels_global", "reflejo_rotuliano", "reflejo_aquileo"],
    citationIds: ["nice_ng59", "chou_2007"],
    treatment: {
      sessions: 8,
      frequency: "2 sesiones por semana las primeras 3 semanas, luego 1",
      durationMin: 45,
      agents: ["Educación en dolor", "Calor superficial", "TENS si dolor agudo"],
      exerciseIds: ["puente", "bird_dog", "gato_camello", "caminata", "respiracion_diafragmatica"],
      education:
        "Permanecer activo. Evitar reposo en cama. Explicar pronóstico favorable en la mayoría de los episodios (NICE NG59).",
      precautions: "Revalorar banderas rojas en cada visita. No forzar flexión sostenida si aumenta el dolor.",
    },
    objectives: [
      "Reducir el dolor lumbar en actividad a ≤3/10",
      "Retomar marcha continua de 30 minutos",
      "Recuperar independencia en vestido y calzado",
    ],
    expectedPattern: [
      "dolor lumbar", "mecánico", "sin déficit", "lasègue negativo",
    ],
  },
  {
    id: "radiculopatia_lumbosacra",
    name: "Radiculopatía lumbosacra (ciática)",
    icd10: "M54.3",
    category: "neurologico",
    regions: ["lumbar", "miembro_inferior"],
    ageHint: "adulto",
    keywords: [
      "ciatica", "ciático", "radiculopatia", "irradiado", "hormigueo pierna",
      "l5", "s1", "dermatoma", "lasègue", "slump",
    ],
    signs: [
      { text: "Lasègue positivo", weight: 4 },
      { text: "Slump positivo", weight: 3 },
      { text: "hiporreflexia aquilea o rotuliana", weight: 3 },
      { text: "debilidad selectiva L4 L5 o S1", weight: 3 },
      { text: "hipoestesia dermatomérica", weight: 3 },
    ],
    symptoms: [
      { text: "dolor lumbar irradiado por debajo de la rodilla", weight: 4 },
      { text: "hormigueo o adormecimiento en pie o pierna", weight: 3 },
      { text: "dolor al toser o estornudar", weight: 2 },
      { text: "empeora al sentarse", weight: 2 },
    ],
    rulingIn: [
      "Dolor irradiado con distribución dermatomérica",
      "Lasègue o Slump positivo",
      "Déficit motor, sensitivo o reflejo coherente con una raíz",
    ],
    rulingOut: [
      "Dolor solo axial sin irradiación",
      "Signos de cola de caballo (urgencia)",
      "Claudicación que mejora al flexionar (estenosis)",
    ],
    suggestedTests: [
      "vas", "lasegue", "slump", "reflejo_rotuliano", "reflejo_aquileo",
      "daniels_global", "sensibilidad",
    ],
    citationIds: ["nass_lumbar_radic", "nice_ng59", "deyo_2016"],
    treatment: {
      sessions: 10,
      frequency: "2 a 3 sesiones por semana",
      durationMin: 50,
      agents: ["Educación", "Ejercicio dirigido", "TENS", "Tracción solo si hay indicación individualizada"],
      exerciseIds: ["nervio_deslizamiento", "puente", "bird_dog", "extension_mckenzie", "caminata"],
      education:
        "La mayoría de las radiculopatías discogénicas mejoran en semanas a meses. Evitar cirugías precipitadas si no hay déficit progresivo (Deyo, NEJM 2016; NICE NG59).",
      precautions: "Vigilancia de déficit progresivo, retención urinaria o anestesia en silla de montar.",
    },
    objectives: [
      "Disminuir el dolor irradiado a ≤3/10",
      "Recuperar dorsiflexión o flexión plantar simétrica",
      "Caminar 20 minutos sin claudicación radicular",
    ],
    expectedPattern: [
      "irradiado", "dermatoma", "lasègue", "hormigueo", "hiporreflexia",
    ],
  },
  {
    id: "hernia_discal_lumbar",
    name: "Hernia discal lumbar con compromiso radicular",
    icd10: "M51.1",
    category: "neurologico",
    regions: ["lumbar", "miembro_inferior"],
    ageHint: "adulto",
    keywords: [
      "hernia", "disco", "protrusion", "extrusion", "l4-l5", "l5-s1",
    ],
    signs: [
      { text: "Lasègue positivo a menos de 60°", weight: 4 },
      { text: "pérdida de lordosis y actitud antálgica", weight: 2 },
      { text: "déficit motor de un miotoma", weight: 3 },
    ],
    symptoms: [
      { text: "inicio agudo al cargar o flexionar", weight: 3 },
      { text: "dolor irradiado a pierna", weight: 3 },
      { text: "peor al sentarse y al flexionar", weight: 2 },
      { text: "alivio relativo en decúbito", weight: 1 },
    ],
    rulingIn: [
      "Inicio mecánico con dolor radicular",
      "Neurodinamia positiva",
      "Concordancia clínica con raíz L5 o S1",
    ],
    rulingOut: [
      "Síndrome de cola de caballo",
      "Estenosis del adulto mayor con claudicación en extensión",
      "Patología inflamatoria con rigidez prolongada",
    ],
    suggestedTests: ["vas", "lasegue", "slump", "daniels_global", "reflejo_aquileo", "reflejo_rotuliano", "sensibilidad"],
    citationIds: ["deyo_2016", "nass_lumbar_radic", "nice_ng59"],
    treatment: {
      sessions: 12,
      frequency: "2 a 3 sesiones por semana",
      durationMin: 50,
      agents: ["Educación", "Ejercicio", "Terapia manual según tolerancia", "TENS"],
      exerciseIds: ["extension_mckenzie", "nervio_deslizamiento", "puente", "respiracion_diafragmatica"],
      education: "Historia natural favorable en muchos casos a 6–12 semanas. Imagen solo si hay banderas rojas o falla de tratamiento (NICE NG59).",
      precautions: "Derivar si déficit progresivo o sospecha de cola de caballo.",
    },
    objectives: [
      "Centralizar el dolor hacia la zona lumbar",
      "Recuperar tolerancia a la sedestación de 30 minutos",
      "Retomar actividades laborales ligeras",
    ],
    expectedPattern: ["hernia", "lasègue", "irradiado", "flexión"],
  },
  {
    id: "estenosis_lumbar",
    name: "Estenosis lumbar degenerativa",
    icd10: "M48.06",
    category: "musculoesqueletico",
    regions: ["lumbar", "miembro_inferior"],
    ageHint: "mayor",
    keywords: [
      "estenosis", "claudicacion", "neurogenica", "canal estrecho",
      "compra carritos", "mejora al sentarse",
    ],
    signs: [
      { text: "claudicación neurógena en extensión", weight: 4 },
      { text: "alivio en flexión lumbar", weight: 4 },
      { text: "Lasègue a menudo negativo", weight: 2 },
    ],
    symptoms: [
      { text: "dolor o pesadez en piernas al caminar", weight: 4 },
      { text: "mejora al sentarse o al flexionarse", weight: 4 },
      { text: "adulto mayor", weight: 2 },
      { text: "mejor empujando un carrito", weight: 2 },
    ],
    rulingIn: [
      "Claudicación que mejora en flexión",
      "Edad avanzada con síntomas al caminar",
      "Neurodinamia a menudo negativa en reposo",
    ],
    rulingOut: [
      "Claudicación vascular (piel, pulsos, dolor en pantorrilla al esfuerzo que no cambia con la postura lumbar)",
      "Ciática aguda del adulto joven",
    ],
    suggestedTests: ["vas", "tug", "berg", "lasegue", "daniels_global", "reflejo_aquileo"],
    citationIds: ["nass_stenosis"],
    treatment: {
      sessions: 12,
      frequency: "2 sesiones por semana",
      durationMin: 45,
      agents: ["Ejercicio en flexión", "Educación", "Ciclismo estático"],
      exerciseIds: ["inclinacion_pelvica", "rodilla_al_pecho", "bicicleta", "puente"],
      education: "El ejercicio y la fisioterapia son primera línea en estenosis sintomática sin déficit grave (NASS 2013).",
      precautions: "Descartar claudicación vascular y cauda equina.",
    },
    objectives: [
      "Aumentar la distancia de marcha sin parar",
      "Reducir dolor en piernas al caminar",
      "Mantener independencia comunitaria",
    ],
    expectedPattern: ["claudicación", "flexión", "adulto mayor", "caminar"],
  },
  {
    id: "cervicalgia_mecanica",
    name: "Dolor cervical inespecífico (cervicalgia mecánica)",
    icd10: "M54.2",
    category: "musculoesqueletico",
    regions: ["cervical"],
    ageHint: "cualquier",
    keywords: [
      "cervicalgia", "cuello", "dolor de cuello", "rigidez cervical", "contractura cuello",
    ],
    signs: [
      { text: "limitación de movilidad cervical", weight: 3 },
      { text: "dolor a la palpación de músculos paravertebrales", weight: 2 },
      { text: "Spurling negativo", weight: 2 },
    ],
    symptoms: [
      { text: "dolor de cuello sin irradiación al brazo", weight: 3 },
      { text: "cefalea tensional asociada", weight: 1 },
      { text: "empeora con posturas mantenidas", weight: 2 },
    ],
    rulingIn: ["Dolor axial cervical", "Sin déficit neurológico", "Spurling negativo"],
    rulingOut: ["Braquialgia con Spurling positivo", "Signos de mielopatía", "Trauma con sospecha de fractura"],
    suggestedTests: ["vas", "spurling", "distraccion_cervical", "romberg", "daniels_global"],
    citationIds: ["jospt_neck_2017"],
    treatment: {
      sessions: 8,
      frequency: "2 sesiones por semana",
      durationMin: 40,
      agents: ["Terapia manual", "Ejercicio", "Educación postural", "Calor"],
      exerciseIds: ["retraccion_cervical", "rotacion_cervical", "escapulas", "respiracion_diafragmatica"],
      education: "Movilidad precoz y ejercicio. Evitar collares prolongados (CPG JOSPT 2017).",
      precautions: "Aplicar reglas canadienses de C-spine si hay trauma.",
    },
    objectives: [
      "Recuperar rotación cervical funcional (conducir, revisar el hombro)",
      "Dolor de cuello ≤3/10 en el trabajo",
    ],
    expectedPattern: ["cuello", "sin irradiación", "mecánico"],
  },
  {
    id: "radiculopatia_cervical",
    name: "Radiculopatía cervical",
    icd10: "M54.12",
    category: "neurologico",
    regions: ["cervical", "miembro_superior"],
    ageHint: "adulto",
    keywords: [
      "radiculopatia cervical", "braquialgia", "hormigueo brazo", "c6", "c7",
      "spurling", "dolor al brazo",
    ],
    signs: [
      { text: "Spurling positivo", weight: 4 },
      { text: "distracción cervical que alivia", weight: 3 },
      { text: "hiporreflexia bicipital o tricipital", weight: 3 },
      { text: "debilidad miotomal", weight: 3 },
    ],
    symptoms: [
      { text: "dolor de cuello irradiado a brazo o mano", weight: 4 },
      { text: "hormigueo en dedos", weight: 3 },
      { text: "peor al extender o inclinar el cuello", weight: 2 },
    ],
    rulingIn: ["Spurling positivo", "Síntomas en un dermatoma", "Alivio con distracción"],
    rulingOut: ["Mielopatía (hiperreflexia, Babinski, torpeza de manos)", "Síndrome de túnel carpiano puro"],
    suggestedTests: [
      "vas", "spurling", "distraccion_cervical", "ulnt1", "reflejo_bicipital",
      "reflejo_tricipital", "daniels_global", "sensibilidad",
    ],
    citationIds: ["nass_cervical_radic", "jospt_neck_2017"],
    treatment: {
      sessions: 10,
      frequency: "2 sesiones por semana",
      durationMin: 45,
      agents: ["Ejercicio", "Movilización", "Tracción intermitente si hay alivio", "Educación"],
      exerciseIds: ["retraccion_cervical", "nervio_deslizamiento_ms", "escapulas", "rotacion_cervical"],
      education: "Curso a menudo autolimitado. Cirugía si déficit progresivo o dolor intratable.",
      precautions: "Descartar mielopatía cervical.",
    },
    objectives: [
      "Reducir dolor irradiado al miembro superior",
      "Recuperar fuerza de agarre y de deltoides o tríceps según raíz",
    ],
    expectedPattern: ["brazo", "spurling", "dermatoma", "cuello"],
  },
  {
    id: "mielopatia_cervical",
    name: "Mielopatía cervical degenerativa",
    icd10: "M47.12",
    category: "urgente",
    regions: ["cervical", "global"],
    ageHint: "mayor",
    keywords: [
      "mielopatia", "torpeza de manos", "hiperreflexia", "babinski",
      "inestabilidad marcha", "clonus",
    ],
    signs: [
      { text: "hiperreflexia", weight: 4 },
      { text: "Babinski positivo", weight: 4 },
      { text: "clonus", weight: 3 },
      { text: "alteración de la marcha", weight: 3 },
    ],
    symptoms: [
      { text: "torpeza de las manos", weight: 4 },
      { text: "inestabilidad al caminar", weight: 3 },
      { text: "entumecimiento bilateral", weight: 2 },
    ],
    rulingIn: ["Signos de neurona motora superior", "Torpeza bimanual", "Alteración de marcha"],
    rulingOut: ["Radiculopatía pura sin signos largos"],
    suggestedTests: ["babinski", "clonus", "romberg", "reflejo_bicipital", "daniels_global", "tug"],
    citationIds: ["fehlings_2017"],
    treatment: {
      sessions: 0,
      frequency: "Derivar; la fisioterapia no sustituye la evaluación quirúrgica",
      durationMin: 30,
      agents: ["No aplicar manipulación cervical"],
      exerciseIds: ["respiracion_diafragmatica"],
      education: "La mielopatía moderada-grave requiere evaluación quirúrgica (Fehlings 2017).",
      precautions: "Bandera roja. Evitar movilizaciones en extremo de rango.",
    },
    objectives: ["Derivar a neurocirugía o columna", "Preservar seguridad en la marcha mientras se evalúa"],
    expectedPattern: ["babinski", "hiperreflexia", "torpeza", "mielopatía"],
  },
  {
    id: "manguito_rotador",
    name: "Síndrome del manguito rotador / tendinopatía del supraespinoso",
    icd10: "M75.1",
    category: "musculoesqueletico",
    regions: ["hombro"],
    ageHint: "adulto",
    keywords: [
      "hombro", "manguito", "supraespinoso", "impingement", "subacromial",
      "hawkins", "neer", "jobe", "dolor al peinarse",
    ],
    signs: [
      { text: "Hawkins-Kennedy positivo", weight: 3 },
      { text: "Neer positivo", weight: 3 },
      { text: "Jobe doloroso o débil", weight: 4 },
      { text: "arco doloroso 60-120", weight: 3 },
    ],
    symptoms: [
      { text: "dolor lateral de hombro al elevar el brazo", weight: 4 },
      { text: "dolor nocturno al acostarse sobre el lado", weight: 2 },
      { text: "dificultad para peinarse o abrocharse", weight: 2 },
    ],
    rulingIn: ["Arco doloroso", "Tests de conflicto positivos", "Debilidad o dolor en Jobe"],
    rulingOut: ["Pérdida global de ROM pasivo (capsulitis)", "Drop arm (rotura masiva)"],
    suggestedTests: ["vas", "hawkins", "neer", "jobe", "drop_arm", "speed", "daniels_global"],
    citationIds: ["aaos_rc", "kuhn_2009"],
    treatment: {
      sessions: 10,
      frequency: "2 sesiones por semana",
      durationMin: 45,
      agents: ["Ejercicio de manguito y escapulares", "Educación de carga", "Hielo o calor según fase"],
      exerciseIds: ["pendulos", "rotacion_externa_banda", "escapulas", "elevacion_plano_escapular"],
      education: "El ejercicio es el tratamiento de primera línea en impingement y tendinopatía (Kuhn 2009; AAOS).",
      precautions: "Si drop arm o pérdida grave de fuerza, valorar imagen y derivación.",
    },
    objectives: [
      "Elevar el brazo por encima de la cabeza con dolor ≤3/10",
      "Dormir sobre el lado afectado",
      "Retomar actividades laborales por encima del hombro",
    ],
    expectedPattern: ["hombro", "elevación", "hawkins", "arco doloroso"],
  },
  {
    id: "capsulitis_adhesiva",
    name: "Capsulitis adhesiva (hombro congelado)",
    icd10: "M75.0",
    category: "musculoesqueletico",
    regions: ["hombro"],
    ageHint: "adulto",
    keywords: [
      "hombro congelado", "capsulitis", "rigidez hombro", "diabetes hombro",
      "perdida de rotacion externa",
    ],
    signs: [
      { text: "pérdida de rotación externa pasiva", weight: 4 },
      { text: "limitación global del ROM pasivo y activo", weight: 4 },
      { text: "patrón capsular", weight: 3 },
    ],
    symptoms: [
      { text: "dolor y rigidez progresiva de hombro", weight: 3 },
      { text: "dificultad para alcanzar la espalda o el cinturón", weight: 3 },
      { text: "antecedente de diabetes o tiroides", weight: 2 },
    ],
    rulingIn: ["Pérdida de ROM pasivo, sobre todo rotación externa", "Patrón capsular"],
    rulingOut: ["ROM pasivo conservado con dolor activo (manguito)", "Artropatía glenohumeral avanzada"],
    suggestedTests: ["vas", "capsulitis_rom", "hawkins", "jobe"],
    citationIds: ["jospt_shoulder_2020"],
    treatment: {
      sessions: 12,
      frequency: "1 a 2 sesiones por semana durante 8–12 semanas",
      durationMin: 45,
      agents: ["Movilización según estadio", "Ejercicio en rango tolerable", "Educación sobre historia natural"],
      exerciseIds: ["pendulos", "rotacion_externa_banda", "deslizamiento_mesa", "respiracion_diafragmatica"],
      education: "Curso de 12–24 meses. El tratamiento alivia; no forzar en fase inflamatoria (JOSPT CPG).",
      precautions: "No estirar agresivamente en fase aguda.",
    },
    objectives: [
      "Ganar rotación externa pasiva",
      "Poder abrocharse el sostén o meter la camisa",
      "Dolor nocturno ≤3/10",
    ],
    expectedPattern: ["rigidez", "pasivo", "rotación externa", "congelado"],
  },
  {
    id: "epicondilalgia_lateral",
    name: "Epicondilalgia lateral (codo de tenista)",
    icd10: "M77.1",
    category: "musculoesqueletico",
    regions: ["codo"],
    ageHint: "adulto",
    keywords: [
      "epicondilitis", "codo de tenista", "epicondilo", "cozen", "extensores muneca",
    ],
    signs: [
      { text: "Cozen positivo", weight: 4 },
      { text: "Mill positivo", weight: 3 },
      { text: "dolor a la palpación del epicóndilo lateral", weight: 3 },
    ],
    symptoms: [
      { text: "dolor lateral de codo al agarrar", weight: 4 },
      { text: "dolor al servir una taza o usar el ratón", weight: 3 },
    ],
    rulingIn: ["Dolor en epicóndilo con tests de carga de extensores"],
    rulingOut: ["Cervicobraquialgia C6–C7", "Atrapamiento del nervio interóseo posterior"],
    suggestedTests: ["vas", "cozen", "mills", "daniels_global", "spurling"],
    citationIds: ["coombes_2015"],
    treatment: {
      sessions: 8,
      frequency: "1 a 2 sesiones por semana",
      durationMin: 40,
      agents: ["Ejercicio de carga progresiva", "Educación laboral", "Hielo postesfuerzo"],
      exerciseIds: ["extensor_excentrico", "prono_supinacion", "agarre_suave"],
      education: "La carga progresiva del tendón es el eje (Coombes, Vicenzino).",
      precautions: "Evitar infiltraciones repetidas como primera línea.",
    },
    objectives: ["Agarrar y levantar 1 kg sin dolor >3/10", "Retomar trabajo de escritorio o deporte"],
    expectedPattern: ["codo", "epicóndilo", "agarre", "cozen"],
  },
  {
    id: "tunel_carpiano",
    name: "Síndrome del túnel carpiano",
    icd10: "G56.0",
    category: "neurologico",
    regions: ["muneca", "mano"],
    ageHint: "adulto",
    keywords: [
      "tunel carpiano", "mediano", "hormigueo dedos", "phalen", "tinel",
      "adormecimiento nocturno mano",
    ],
    signs: [
      { text: "Phalen positivo", weight: 4 },
      { text: "Tinel positivo", weight: 3 },
      { text: "hipoestesia en territorio mediano", weight: 3 },
      { text: "debilidad de abductor corto del pulgar", weight: 2 },
    ],
    symptoms: [
      { text: "hormigueo nocturno en pulgar índice y medio", weight: 4 },
      { text: "sacudida de la mano que alivia", weight: 2 },
      { text: "torpeza para abotonarse", weight: 2 },
    ],
    rulingIn: ["Síntomas en territorio mediano", "Phalen o Tinel positivo"],
    rulingOut: ["Radiculopatía C6–C7", "Polineuropatía"],
    suggestedTests: ["vas", "phalen", "tinel_carpiano", "ulnt1", "daniels_global", "sensibilidad"],
    citationIds: ["padua_2016"],
    treatment: {
      sessions: 6,
      frequency: "1 sesión por semana más plan casero",
      durationMin: 30,
      agents: ["Férula nocturna", "Educación ergonómica", "Deslizamientos neurales"],
      exerciseIds: ["deslizamiento_mediano", "movilidad_muneca", "tendon_gliding"],
      education: "Férula nocturna y modificación de carga. Derivar si atrofia tenar o fallo conservador (Padua, Lancet Neurol).",
      precautions: "No retrasar derivación si hay atrofia o debilidad marcada.",
    },
    objectives: ["Reducir despertares nocturnos por hormigueo", "Mejorar destreza fina"],
    expectedPattern: ["mediano", "nocturno", "phalen", "pulgar"],
  },
  {
    id: "gonartrosis",
    name: "Osteoartritis de rodilla (gonartrosis)",
    icd10: "M17.1",
    category: "musculoesqueletico",
    regions: ["rodilla"],
    ageHint: "mayor",
    keywords: [
      "gonartrosis", "artrosis rodilla", "osteoartritis rodilla", "crepitacion",
      "rigidez rodilla",
    ],
    signs: [
      { text: "crepitación", weight: 2 },
      { text: "dolor a la carga y a la palpación de interlínea", weight: 3 },
      { text: "limitación de flexión o extensión", weight: 2 },
      { text: "debilidad de cuádriceps", weight: 2 },
    ],
    symptoms: [
      { text: "dolor de rodilla al subir escaleras", weight: 3 },
      { text: "rigidez menor de 30 minutos", weight: 2 },
      { text: "adulto mayor", weight: 2 },
      { text: "empeora al final del día", weight: 1 },
    ],
    rulingIn: ["Dolor mecánico de rodilla en edad media-avanzada", "Rigidez breve"],
    rulingOut: ["Bloqueo verdadero y McMurray (menisco)", "Rodilla caliente con fiebre"],
    suggestedTests: ["vas", "daniels_global", "mcmurray", "lachman", "chair_stand", "tug"],
    citationIds: ["oarsi_2019", "acr_oa_2020"],
    treatment: {
      sessions: 12,
      frequency: "2 sesiones por semana",
      durationMin: 45,
      agents: ["Ejercicio (fuerza y aeróbico)", "Educación", "Pérdida de peso si hay sobrepeso", "Frío postejercicio"],
      exerciseIds: ["sentadilla_asistida", "extension_rodilla", "puente", "caminata", "bicicleta"],
      education: "El ejercicio es tratamiento central (OARSI 2019; ACR 2020). Evitar reposo prolongado.",
      precautions: "Derivar si bloqueo, inestabilidad o sospecha inflamatoria.",
    },
    objectives: [
      "Bajar un piso de escaleras con dolor ≤3/10",
      "Caminar 30 minutos",
      "Fuerza de cuádriceps ≥4/5",
    ],
    expectedPattern: ["rodilla", "escaleras", "artrosis", "carga"],
  },
  {
    id: "dolor_femoropatelar",
    name: "Síndrome de dolor femoropatelar",
    icd10: "M22.2",
    category: "musculoesqueletico",
    regions: ["rodilla"],
    ageHint: "adulto",
    keywords: [
      "femoropatelar", "rotula", "dolor anterior rodilla", "cine", "sentadillas",
    ],
    signs: [
      { text: "dolor a la compresión patelar", weight: 3 },
      { text: "Clarke positivo", weight: 2 },
      { text: "debilidad de glúteo medio o cuádriceps", weight: 2 },
    ],
    symptoms: [
      { text: "dolor anterior de rodilla al estar sentado rato", weight: 3 },
      { text: "dolor en sentadillas o bajando escaleras", weight: 4 },
      { text: "adulto joven o corredor", weight: 2 },
    ],
    rulingIn: ["Dolor anterior relacionado con carga en flexión", "Sin inestabilidad ligamentosa"],
    rulingOut: ["Inestabilidad de LCA", "Artrosis avanzada del adulto mayor"],
    suggestedTests: ["vas", "clarke", "trendelenburg", "ober", "daniels_global", "chair_stand"],
    citationIds: ["jospt_pfps"],
    treatment: {
      sessions: 8,
      frequency: "2 sesiones por semana",
      durationMin: 45,
      agents: ["Ejercicio de cadera y rodilla", "Educación de carga", "Reentrenamiento de carrera si aplica"],
      exerciseIds: ["sentadilla_asistida", "almeja", "puente", "step_down"],
      education: "Combinar ejercicio de cadera y rodilla (CPG JOSPT 2019).",
      precautions: "Evitar sentadillas profundas dolorosas al inicio.",
    },
    objectives: ["Bajar escaleras sin dolor >3/10", "Retomar carrera o deporte de forma gradual"],
    expectedPattern: ["anterior", "rótula", "sentadilla", "escaleras"],
  },
  {
    id: "coxartrosis",
    name: "Osteoartritis de cadera (coxartrosis)",
    icd10: "M16.1",
    category: "musculoesqueletico",
    regions: ["cadera"],
    ageHint: "mayor",
    keywords: [
      "coxartrosis", "artrosis cadera", "dolor inguinal", "faber", "rotacion interna cadera",
    ],
    signs: [
      { text: "limitación de rotación interna", weight: 4 },
      { text: "FABER positivo inguinal", weight: 3 },
      { text: "Trendelenburg", weight: 2 },
    ],
    symptoms: [
      { text: "dolor inguinal o de glúteo a la carga", weight: 4 },
      { text: "dificultad para calzarse", weight: 2 },
      { text: "rigidez de cadera", weight: 2 },
    ],
    rulingIn: ["Dolor inguinal con pérdida de rotación interna", "Edad media-avanzada"],
    rulingOut: ["Lumbalgia referida", "Trocanteritis aislada"],
    suggestedTests: ["vas", "faber", "fadir", "trendelenburg", "thomas", "tug", "daniels_global"],
    citationIds: ["jospt_hip_oa", "oarsi_2019"],
    treatment: {
      sessions: 12,
      frequency: "2 sesiones por semana",
      durationMin: 45,
      agents: ["Ejercicio", "Educación", "Ayudas de marcha si hay claudicación"],
      exerciseIds: ["puente", "almeja", "sentadilla_asistida", "caminata"],
      education: "Ejercicio y educación como primera línea (OARSI, JOSPT hip OA).",
      precautions: "FADIR muy doloroso en joven: considerar choque femoroacetabular.",
    },
    objectives: ["Calzarse sin ayuda", "Caminar 20 minutos con dolor ≤3/10"],
    expectedPattern: ["ingle", "rotación interna", "cadera", "carga"],
  },
  {
    id: "esguince_tobillo",
    name: "Esguince lateral de tobillo",
    icd10: "S93.4",
    category: "musculoesqueletico",
    regions: ["tobillo"],
    ageHint: "cualquier",
    keywords: [
      "esguince", "tobillo", "inversion", "lpea", "peroneoastragalino", "ottawa",
    ],
    signs: [
      { text: "cajón anterior de tobillo positivo", weight: 3 },
      { text: "dolor a la palpación del LPAA", weight: 3 },
      { text: "Ottawa negativo (sin criterio de rx)", weight: 2 },
    ],
    symptoms: [
      { text: "torcedura en inversión", weight: 4 },
      { text: "hinchazón lateral", weight: 3 },
      { text: "dolor al apoyar", weight: 2 },
    ],
    rulingIn: ["Mecanismo de inversión", "Dolor en LPAA", "Ottawa negativo o ya imagenada"],
    rulingOut: ["Ottawa positivo (fractura)", "Thompson positivo (Aquiles)"],
    suggestedTests: ["vas", "ottawa_tobillo", "cajon_anterior_tobillo", "thompson", "daniels_global"],
    citationIds: ["vuurberg_2018", "downs_ottawa"],
    treatment: {
      sessions: 6,
      frequency: "2 a 3 sesiones la primera semana, luego 1–2",
      durationMin: 40,
      agents: ["Apoyo precoz protegido", "Hielo y compresión en fase aguda", "Ejercicio de equilibrio"],
      exerciseIds: ["dorsiflexion", "equilibrio_unipodal", "abecedario_tobillo", "caminata"],
      education: "Movilización precoz superior al inmovilizar (BJSM 2018). Usar Ottawa para decidir imagen.",
      precautions: "Si Ottawa positivo, derivar a radiografía antes de cargar.",
    },
    objectives: ["Apoyo completo simétrico", "Retomar deporte con equilibrio unipodal estable"],
    expectedPattern: ["inversión", "tobillo", "hinchazón", "LPAA"],
  },
  {
    id: "fascitis_plantar",
    name: "Fasciopatía plantar",
    icd10: "M72.2",
    category: "musculoesqueletico",
    regions: ["pie"],
    ageHint: "adulto",
    keywords: [
      "fascitis", "fasciopatia", "talon", "primeros pasos", "windlass",
    ],
    signs: [
      { text: "Windlass positivo", weight: 4 },
      { text: "dolor en tubérculo medial del calcáneo", weight: 4 },
    ],
    symptoms: [
      { text: "dolor de talón en los primeros pasos de la mañana", weight: 5 },
      { text: "empeora tras reposo", weight: 2 },
    ],
    rulingIn: ["Dolor de talón al iniciar la marcha", "Windlass positivo"],
    rulingOut: ["Fractura de estrés", "Síndrome del túnel tarsiano", "Espondiloartritis con entesitis"],
    suggestedTests: ["vas", "windlass", "daniels_global"],
    citationIds: ["jospt_plantar"],
    treatment: {
      sessions: 8,
      frequency: "1 a 2 sesiones por semana",
      durationMin: 35,
      agents: ["Carga progresiva de fascia y gemelo", "Educación de calzado", "Estiramiento"],
      exerciseIds: ["estiramiento_fascia", "elevacion_talon", "masaje_pelota"],
      education: "Carga progresiva; las ondas de choque se reservan a casos rebeldes (JOSPT 2014).",
      precautions: "Dolor nocturno o bilateral en joven: pensar en espondiloartritis.",
    },
    objectives: ["Primeros pasos matutinos con dolor ≤2/10", "Caminar 30 minutos"],
    expectedPattern: ["talón", "mañana", "fascia", "windlass"],
  },
  {
    id: "tendinopatia_aquiles",
    name: "Tendinopatía aquilea de porción media",
    icd10: "M76.6",
    category: "musculoesqueletico",
    regions: ["tobillo"],
    ageHint: "adulto",
    keywords: [
      "aquiles", "tendinopatia aquilea", "gemelo", "corredor", "thompson negativo",
    ],
    signs: [
      { text: "dolor a 2-6 cm de la inserción", weight: 4 },
      { text: "Thompson negativo", weight: 2 },
      { text: "engrosamiento del tendón", weight: 2 },
    ],
    symptoms: [
      { text: "dolor de Aquiles al correr o saltar", weight: 4 },
      { text: "rigidez matutina del tendón", weight: 2 },
    ],
    rulingIn: ["Dolor en porción media", "Carga reproducible", "Thompson negativo"],
    rulingOut: ["Rotura completa (Thompson positivo)", "Entesitis insercional aislada"],
    suggestedTests: ["vas", "thompson", "daniels_global"],
    citationIds: ["jospt_achilles"],
    treatment: {
      sessions: 10,
      frequency: "1 sesión semanal más plan diario de carga",
      durationMin: 40,
      agents: ["Protocolo de carga progresiva", "Educación de carrera"],
      exerciseIds: ["elevacion_talon", "elevacion_talon_excentrica", "caminata"],
      education: "La carga progresiva es el tratamiento de elección (JOSPT 2018).",
      precautions: "Thompson positivo: derivación urgente.",
    },
    objectives: ["Correr 20 minutos con dolor ≤3/10", "Elevar talones a una pierna"],
    expectedPattern: ["Aquiles", "correr", "porción media"],
  },
  {
    id: "parkinson",
    name: "Enfermedad de Parkinson (abordaje fisioterapéutico)",
    icd10: "G20",
    category: "neurologico",
    regions: ["equilibrio", "global"],
    ageHint: "mayor",
    keywords: [
      "parkinson", "temblor de reposo", "rigidez", "bradicinesia", "freezing",
      "festinacion", "marcha arrastrada",
    ],
    signs: [
      { text: "bradicinesia", weight: 4 },
      { text: "rigidez en rueda dentada", weight: 3 },
      { text: "freezing o festinación", weight: 3 },
      { text: "TUG prolongado", weight: 2 },
    ],
    symptoms: [
      { text: "lentitud al moverse", weight: 3 },
      { text: "caídas o near-falls", weight: 2 },
      { text: "dificultad para girar en la cama", weight: 2 },
    ],
    rulingIn: ["Diagnóstico médico de Parkinson", "Alteración de marcha y equilibrio"],
    rulingOut: ["Parkinsonismo atípico con caídas precoces graves (derivar)"],
    suggestedTests: ["tug", "berg", "tinetti", "updrs_marcha", "chair_stand", "vas"],
    citationIds: ["nice_ng71", "keus_kngf"],
    treatment: {
      sessions: 12,
      frequency: "2 sesiones por semana más ejercicio diario",
      durationMin: 50,
      agents: ["Ejercicio aeróbico", "Entrenamiento de amplitud", "Estrategias de cues", "Equilibrio"],
      exerciseIds: ["grandes_amplitudes", "caminata", "equilibrio_unipodal", "sentadilla_asistida"],
      education: "El ejercicio específico mejora movilidad (NICE NG71; guía europea KNGF).",
      precautions: "Hipotensión, freezing en umbrales, riesgo de caída.",
    },
    objectives: ["Reducir tiempo de TUG", "Girar en la cama con menos ayuda", "Caminar en comunidad con seguridad"],
    expectedPattern: ["parkinson", "freezing", "bradicinesia", "caídas"],
  },
  {
    id: "acv_hemiparesia",
    name: "Hemiparesia residual post-ACV",
    icd10: "I69.3",
    category: "neurologico",
    regions: ["global"],
    ageHint: "mayor",
    keywords: [
      "acv", "ictus", "hemiparesia", "hemiplejia", "espasticidad", "facio",
    ],
    signs: [
      { text: "debilidad hemicorporal", weight: 5 },
      { text: "Babinski positivo", weight: 2 },
      { text: "espasticidad", weight: 2 },
      { text: "Barthel reducido", weight: 2 },
    ],
    symptoms: [
      { text: "dificultad para caminar tras ictus", weight: 4 },
      { text: "pérdida de uso del brazo", weight: 3 },
    ],
    rulingIn: ["Antecedente de ACV", "Déficit piramidal unilateral"],
    rulingOut: ["Déficit fluctuante agudo (derivar a urgencias)"],
    suggestedTests: ["daniels_global", "barthel", "tug", "berg", "babinski", "sensibilidad", "vas"],
    citationIds: ["aha_stroke_2016"],
    treatment: {
      sessions: 16,
      frequency: "3 sesiones por semana en fase subaguda, 2 en crónica",
      durationMin: 60,
      agents: ["Tarea específica", "Entrenamiento de marcha", "Fortalecimiento", "Terapia de constraint si aplica"],
      exerciseIds: ["sentadilla_asistida", "caminata", "alcance_ms", "equilibrio_unipodal"],
      education: "Alta intensidad de práctica de tareas (AHA/ASA 2016).",
      precautions: "Hombro subluxado, disfagia, riesgo cardiovascular.",
    },
    objectives: ["Marcha independiente o con ayuda mínima en domicilio", "Uso del miembro plegado en AVD"],
    expectedPattern: ["ictus", "hemiparesia", "piramidal"],
  },
  {
    id: "esclerosis_multiple",
    name: "Esclerosis múltiple (abordaje fisioterapéutico)",
    icd10: "G35",
    category: "neurologico",
    regions: ["global"],
    ageHint: "adulto",
    keywords: [
      "esclerosis multiple", "fatiga", "uhthoff", "espasticidad", "neuritis",
    ],
    signs: [
      { text: "espasticidad variable", weight: 2 },
      { text: "ataxia o Romberg", weight: 2 },
      { text: "fatiga que limita el ejercicio", weight: 3 },
    ],
    symptoms: [
      { text: "fatiga", weight: 3 },
      { text: "empeora con el calor", weight: 2 },
      { text: "alteración de la marcha", weight: 2 },
    ],
    rulingIn: ["Diagnóstico médico de EM", "Síntomas fluctuantes con fatiga"],
    rulingOut: ["Brote agudo con nuevo déficit (derivar a neurología)"],
    suggestedTests: ["tug", "berg", "romberg", "daniels_global", "vas", "finger_nose"],
    citationIds: ["nice_ng220"],
    treatment: {
      sessions: 10,
      frequency: "2 sesiones por semana, dosificar por fatiga",
      durationMin: 45,
      agents: ["Ejercicio aeróbico dosificado", "Fuerza", "Equilibrio", "Gestión de fatiga"],
      exerciseIds: ["caminata", "puente", "equilibrio_unipodal", "respiracion_diafragmatica"],
      education: "Ejercicio es seguro y recomendado (NICE NG220). Evitar sobrecalentamiento.",
      precautions: "Uhthoff: bajar intensidad con calor. Nuevo déficit = brote.",
    },
    objectives: ["Mejorar tolerancia a la fatiga en AVD", "Reducir riesgo de caída"],
    expectedPattern: ["fatiga", "EM", "calor", "espasticidad"],
  },
  {
    id: "neuropatia_diabetica",
    name: "Neuropatía periférica diabética",
    icd10: "E11.40",
    category: "neurologico",
    regions: ["pie", "miembro_inferior"],
    ageHint: "mayor",
    keywords: [
      "neuropatia", "diabetes", "calcetin", "quemazon pies", "monofilamento",
    ],
    signs: [
      { text: "monofilamento alterado", weight: 4 },
      { text: "hipoestesia en calcetín", weight: 4 },
      { text: "hiporreflexia aquilea", weight: 2 },
    ],
    symptoms: [
      { text: "quemazón o hormigueo en pies", weight: 4 },
      { text: "peor por la noche", weight: 2 },
      { text: "diabetes", weight: 3 },
    ],
    rulingIn: ["Patrón de calcetín", "Diabetes", "Pérdida de sensibilidad protectora"],
    rulingOut: ["Radiculopatía unilateral", "Síndrome de Guillain-Barré (agudo y ascendente)"],
    suggestedTests: ["monofilamento", "sensibilidad", "reflejo_aquileo", "romberg", "tug", "vas"],
    citationIds: ["popbusui_2017"],
    treatment: {
      sessions: 8,
      frequency: "1 a 2 sesiones por semana",
      durationMin: 40,
      agents: ["Educación de pie diabético", "Equilibrio", "Ejercicio aeróbico"],
      exerciseIds: ["equilibrio_unipodal", "caminata", "dorsiflexion"],
      education: "Inspección diaria del pie. El ejercicio mejora función (ADA 2017).",
      precautions: "Úlceras, pie de Charcot: derivar.",
    },
    objectives: ["Caminar con seguridad", "Ausencia de lesiones plantares"],
    expectedPattern: ["calcetín", "diabetes", "quemazón", "monofilamento"],
  },
  {
    id: "riesgo_caidas",
    name: "Riesgo de caídas / trastorno del equilibrio en adulto mayor",
    icd10: "R29.6",
    category: "geriatrico",
    regions: ["equilibrio", "global"],
    ageHint: "mayor",
    keywords: [
      "caidas", "equilibrio", "miedo a caer", "fragilidad", "adulto mayor",
    ],
    signs: [
      { text: "TUG prolongado", weight: 4 },
      { text: "Berg bajo", weight: 4 },
      { text: "Tinetti bajo", weight: 3 },
    ],
    symptoms: [
      { text: "caídas de repetición", weight: 4 },
      { text: "miedo a caer", weight: 2 },
      { text: "inestabilidad", weight: 2 },
    ],
    rulingIn: ["Caídas o TUG/Berg alterados en adulto mayor"],
    rulingOut: ["Vértigo posicional puro", "Síncope cardiológico"],
    suggestedTests: ["tug", "berg", "tinetti", "sppb", "chair_stand", "romberg", "vas"],
    citationIds: ["nice_cg161", "ags_bgs_falls"],
    treatment: {
      sessions: 12,
      frequency: "2 sesiones por semana",
      durationMin: 45,
      agents: ["Entrenamiento de equilibrio y fuerza", "Revisión de calzado y hogar"],
      exerciseIds: ["equilibrio_unipodal", "sentadilla_asistida", "caminata", "chair_stand_ej"],
      education: "Programas multifactoriales reducen caídas (NICE CG161, AGS/BGS).",
      precautions: "Síncope, anticoagulados con TCE: derivar.",
    },
    objectives: ["TUG <14 s", "Ninguna caída en 90 días", "Confianza para salir a la calle"],
    expectedPattern: ["caídas", "equilibrio", "adulto mayor", "TUG"],
  },
  {
    id: "vppb",
    name: "Vértigo posicional paroxístico benigno",
    icd10: "H81.1",
    category: "neurologico",
    regions: ["equilibrio"],
    ageHint: "cualquier",
    keywords: [
      "vertigo", "vppb", "dix hallpike", "nistagmo", "al girar en la cama",
    ],
    signs: [
      { text: "Dix-Hallpike positivo", weight: 5 },
      { text: "nistagmo transitorio", weight: 4 },
    ],
    symptoms: [
      { text: "vértigo breve al girar la cabeza o acostarse", weight: 5 },
      { text: "sin hipoacusia ni destellos", weight: 2 },
    ],
    rulingIn: ["Vértigo de segundos con Dix-Hallpike positivo"],
    rulingOut: ["Vértigo continuo con nistagmo espontáneo (neuritis o central)", "Síntomas neurológicos focales"],
    suggestedTests: ["dix_hallpike", "romberg", "tug"],
    citationIds: ["bhattacharyya_2017"],
    treatment: {
      sessions: 3,
      frequency: "1 a 2 sesiones iniciales, control a la semana",
      durationMin: 30,
      agents: ["Maniobra de Epley", "Instrucciones de evitación temporal"],
      exerciseIds: ["brandt_daroff"],
      education: "Las maniobras de reposicionamiento son de primera línea (CPG 2017).",
      precautions: "Nistagmo vertical puro o síntomas centrales: derivar.",
    },
    objectives: ["Resolver vértigo posicional", "Dormir y girar en la cama sin crisis"],
    expectedPattern: ["vértigo", "posicional", "Dix-Hallpike"],
  },
  {
    id: "fibromialgia",
    name: "Fibromialgia",
    icd10: "M79.7",
    category: "musculoesqueletico",
    regions: ["global"],
    ageHint: "adulto",
    keywords: [
      "fibromialgia", "dolor generalizado", "puntos dolorosos", "fatiga cronica",
      "sueño no reparador",
    ],
    signs: [
      { text: "dolor generalizado a la palpación", weight: 3 },
      { text: "exploración neurológica normal", weight: 2 },
    ],
    symptoms: [
      { text: "dolor generalizado de más de 3 meses", weight: 4 },
      { text: "fatiga y sueño no reparador", weight: 3 },
      { text: "niebla mental", weight: 1 },
    ],
    rulingIn: ["Dolor generalizado crónico con sueño y fatiga", "Sin inflamación articular objetiva"],
    rulingOut: ["Enfermedad inflamatoria activa", "Déficit neurológico focal"],
    suggestedTests: ["vas", "berg", "tug", "daniels_global"],
    citationIds: ["eular_fm_2017"],
    treatment: {
      sessions: 10,
      frequency: "1 a 2 sesiones por semana, dosificar",
      durationMin: 40,
      agents: ["Ejercicio aeróbico gradual", "Educación en dolor", "Higiene de sueño"],
      exerciseIds: ["caminata", "respiracion_diafragmatica", "gato_camello", "puente"],
      education: "Ejercicio y educación son las intervenciones con mayor evidencia (EULAR 2017).",
      precautions: "No medicalizar con pasivo exclusivo. Descartar banderas rojas.",
    },
    objectives: ["Caminar 20 minutos la mayoría de los días", "Reducir interferencia del dolor en AVD"],
    expectedPattern: ["generalizado", "fatiga", "sueño", "crónico"],
  },
  {
    id: "espondiloartritis",
    name: "Espondiloartritis axial (sospecha)",
    icd10: "M45",
    category: "musculoesqueletico",
    regions: ["lumbar", "dorsal"],
    ageHint: "adulto",
    keywords: [
      "espondilitis", "espondiloartritis", "rigidez matutina larga",
      "uveitis", "entesitis", "hla-b27", "dolor nocturno inflamatorio",
    ],
    signs: [
      { text: "Schober reducido", weight: 3 },
      { text: "expansión torácica reducida", weight: 2 },
      { text: "dolor sacroilíaco", weight: 3 },
    ],
    symptoms: [
      { text: "dolor lumbar inflamatorio en menor de 45 años", weight: 4 },
      { text: "rigidez matutina mayor de 45 minutos", weight: 4 },
      { text: "mejora con ejercicio no con reposo", weight: 3 },
      { text: "dolor nocturno de segunda mitad", weight: 3 },
    ],
    rulingIn: ["Criterios de dolor inflamatorio", "Inicio <45 años", "Schober reducido"],
    rulingOut: ["Lumbalgia mecánica pura del adulto mayor"],
    suggestedTests: ["schober", "vas", "faber", "windlass"],
    citationIds: ["nice_ng65"],
    treatment: {
      sessions: 10,
      frequency: "2 sesiones por semana coordinadas con reumatología",
      durationMin: 45,
      agents: ["Ejercicio de movilidad y aeróbico", "Educación"],
      exerciseIds: ["gato_camello", "extension_mckenzie", "respiracion_diafragmatica", "caminata"],
      education: "Derivar a reumatología. El ejercicio es parte del tratamiento (NICE NG65).",
      precautions: "No retrasar la derivación. Vigilar uveítis y dolor nocturno intenso.",
    },
    objectives: ["Reducir rigidez matutina", "Mantener movilidad lumbar y torácica"],
    expectedPattern: ["inflamatorio", "rigidez prolongada", "joven", "nocturno"],
  },
  {
    id: "cauda_equina",
    name: "Síndrome de cola de caballo (urgencia)",
    icd10: "G83.4",
    category: "urgente",
    regions: ["lumbar"],
    ageHint: "cualquier",
    keywords: [
      "cola de caballo", "cauda equina", "silla de montar", "retencion urinaria",
      "incontinencia", "anestesia perineal",
    ],
    signs: [
      { text: "anestesia en silla de montar", weight: 5 },
      { text: "retención o incontinencia urinaria", weight: 5 },
      { text: "déficit motor bilateral", weight: 4 },
    ],
    symptoms: [
      { text: "pérdida de control de esfínteres", weight: 5 },
      { text: "adormecimiento genital o anal", weight: 5 },
      { text: "ciática bilateral", weight: 3 },
    ],
    rulingIn: ["Disfunción vesical/intestinal de novo", "Anestesia en silla de montar"],
    rulingOut: [],
    suggestedTests: ["sensibilidad", "daniels_global", "lasegue", "reflejo_aquileo"],
    citationIds: ["todd_cauda", "nice_ng59"],
    treatment: {
      sessions: 0,
      frequency: "No tratar: derivación urgente",
      durationMin: 0,
      agents: [],
      exerciseIds: [],
      education: "Urgencia neuroquirúrgica. No dilatar.",
      precautions: "Traslado inmediato a urgencias.",
    },
    objectives: ["Derivación urgente al servicio de urgencias / neurocirugía"],
    expectedPattern: ["silla de montar", "esfínter", "bilateral"],
  },
  {
    id: "tvp",
    name: "Sospecha de trombosis venosa profunda",
    icd10: "I80.2",
    category: "urgente",
    regions: ["miembro_inferior"],
    ageHint: "cualquier",
    keywords: [
      "tvp", "trombosis", "pantorrilla hinchada", "wells", "homans",
      "dolor gemelo unilateral",
    ],
    signs: [
      { text: "edema unilateral", weight: 4 },
      { text: "pantorrilla caliente y dolorosa", weight: 4 },
      { text: "circunferencia asimétrica", weight: 3 },
    ],
    symptoms: [
      { text: "dolor e hinchazón de una pierna", weight: 4 },
      { text: "cirugía reciente o inmovilización", weight: 3 },
    ],
    rulingIn: ["Edema doloroso unilateral", "Factores de Wells"],
    rulingOut: [],
    suggestedTests: ["vas"],
    citationIds: ["nice_ng158", "wells_2003"],
    treatment: {
      sessions: 0,
      frequency: "No tratar: derivación urgente",
      durationMin: 0,
      agents: [],
      exerciseIds: [],
      education: "No masajear ni aplicar calor. Derivar según NICE NG158.",
      precautions: "Riesgo de TEP.",
    },
    objectives: ["Derivación médica urgente"],
    expectedPattern: ["edema unilateral", "pantorrilla", "caliente"],
  },
  {
    id: "guillain_barre",
    name: "Sospecha de síndrome de Guillain-Barré",
    icd10: "G61.0",
    category: "urgente",
    regions: ["global"],
    ageHint: "cualquier",
    keywords: [
      "guillain", "barre", "paralisis ascendente", "areflexia aguda",
      "postinfeccioso",
    ],
    signs: [
      { text: "debilidad ascendente simétrica aguda", weight: 5 },
      { text: "arreflexia", weight: 4 },
    ],
    symptoms: [
      { text: "debilidad progresiva en días", weight: 5 },
      { text: "infección reciente", weight: 2 },
      { text: "dificultad para caminar de inicio agudo", weight: 3 },
    ],
    rulingIn: ["Debilidad simétrica aguda con arreflexia"],
    rulingOut: [],
    suggestedTests: ["daniels_global", "reflejo_rotuliano", "reflejo_aquileo", "sensibilidad"],
    citationIds: ["willison_gbs"],
    treatment: {
      sessions: 0,
      frequency: "Urgencias",
      durationMin: 0,
      agents: [],
      exerciseIds: [],
      education: "Urgencia neurológica (Lancet 2016).",
      precautions: "Vigilancia respiratoria.",
    },
    objectives: ["Derivación urgente a neurología"],
    expectedPattern: ["ascendente", "agudo", "arreflexia"],
  },
];

export const DIAGNOSIS_BY_ID = Object.fromEntries(DIAGNOSES.map((d) => [d.id, d]));
