import type { Region } from "../types";

export type CatalogExercise = {
  id: string;
  name: string;
  description: string;
  howTo: string;
  region: Region;
  image: string;
};

export const EXERCISES: CatalogExercise[] = [
  {
    id: "puente",
    name: "Puente de glúteos",
    description: "Activa cadena posterior y estabiliza lumbar y cadera.",
    howTo:
      "Decúbito supino, rodillas flexionadas. Eleve la pelvis hasta alinear hombros-cadera-rodillas. Baje con control.",
    region: "lumbar",
    image: "/exercises/puente.svg",
  },
  {
    id: "bird_dog",
    name: "Bird-dog (cuadrupedia contralateral)",
    description: "Control motor lumbar y de tronco.",
    howTo:
      "En cuadrupedia, extienda un brazo y la pierna contraria sin hundir la lumbar. Mantenga 5–8 s.",
    region: "lumbar",
    image: "/exercises/bird_dog.svg",
  },
  {
    id: "gato_camello",
    name: "Gato-camello",
    description: "Movilidad segmentaria toracolumbar.",
    howTo: "En cuadrupedia, alterne flexión y extensión suaves de la columna al ritmo de la respiración.",
    region: "lumbar",
    image: "/exercises/gato_camello.svg",
  },
  {
    id: "caminata",
    name: "Caminata dosificada",
    description: "Ejercicio aeróbico de primera línea en la mayoría de cuadros.",
    howTo: "Camine a paso que permita hablar. Empiece por 10–15 min y suba 5 min cada pocos días.",
    region: "global",
    image: "/exercises/caminata.svg",
  },
  {
    id: "respiracion_diafragmatica",
    name: "Respiración diafragmática",
    description: "Reduce tensión y mejora control de tronco.",
    howTo: "Una mano en el abdomen. Inspire por la nariz inflando el vientre; expire despacio por la boca.",
    region: "global",
    image: "/exercises/respiracion.svg",
  },
  {
    id: "nervio_deslizamiento",
    name: "Deslizamiento del nervio ciático",
    description: "Neurodinamia suave para radiculopatía.",
    howTo:
      "Sentado, extienda la rodilla y dorsiflexione el pie mientras el cuello se extiende; invierta. Sin forzar el dolor irradiado.",
    region: "miembro_inferior",
    image: "/exercises/nervio.svg",
  },
  {
    id: "extension_mckenzie",
    name: "Extensión en prono (McKenzie)",
    description: "Puede centralizar síntomas discogénicos.",
    howTo: "Decúbito prono, extienda los brazos como en cobra suave. Deténgase si el dolor se periferiza.",
    region: "lumbar",
    image: "/exercises/extension.svg",
  },
  {
    id: "inclinacion_pelvica",
    name: "Inclinación pélvica",
    description: "Control lumbopélvico en flexión, útil en estenosis.",
    howTo: "Supino, aplaste la lumbar contra la camilla y suelte. 10 repeticiones lentas.",
    region: "lumbar",
    image: "/exercises/pelvis.svg",
  },
  {
    id: "rodilla_al_pecho",
    name: "Rodilla al pecho",
    description: "Flexión lumbar asistida.",
    howTo: "Supino, lleve una o ambas rodillas al pecho con las manos. Sin dolor irradiado.",
    region: "lumbar",
    image: "/exercises/rodilla_pecho.svg",
  },
  {
    id: "bicicleta",
    name: "Bicicleta estática",
    description: "Aeróbico en flexión, bien tolerado en estenosis y gonartrosis.",
    howTo: "Asiento alto, resistencia baja a moderada, 10–20 min.",
    region: "global",
    image: "/exercises/bici.svg",
  },
  {
    id: "retraccion_cervical",
    name: "Retracción cervical (chin tuck)",
    description: "Control motor cervical profundo.",
    howTo: "Siéntese erguido. Lleve la barbilla hacia atrás como haciendo una papada, sin inclinar la cabeza.",
    region: "cervical",
    image: "/exercises/chin_tuck.svg",
  },
  {
    id: "rotacion_cervical",
    name: "Rotación cervical activa",
    description: "Movilidad cervical en rango indoloro.",
    howTo: "Gire la cabeza hacia cada lado como para mirar por encima del hombro. 8–10 repeticiones.",
    region: "cervical",
    image: "/exercises/cuello.svg",
  },
  {
    id: "escapulas",
    name: "Estabilización escapular (filas)",
    description: "Control de trapecio medio e inferior.",
    howTo: "Elásticos a la altura del pecho, apriete omóplatos hacia atrás y abajo.",
    region: "hombro",
    image: "/exercises/escapulas.svg",
  },
  {
    id: "nervio_deslizamiento_ms",
    name: "Deslizamiento del nervio mediano",
    description: "Neurodinamia de miembro superior.",
    howTo: "Extienda codo y muñeca mientras el cuello se inclina al lado contrario; invierta. Suave.",
    region: "miembro_superior",
    image: "/exercises/nervio_ms.svg",
  },
  {
    id: "pendulos",
    name: "Péndulos de Codman",
    description: "Movilidad precoz de hombro con poca carga.",
    howTo: "Apoye la mano sana en una mesa, deje colgar el brazo y dibuje círculos pequeños.",
    region: "hombro",
    image: "/exercises/pendulos.svg",
  },
  {
    id: "rotacion_externa_banda",
    name: "Rotación externa con banda",
    description: "Fortalecimiento de infraespinoso y redondo menor.",
    howTo: "Codo a 90° pegado al cuerpo, gire el antebrazo hacia fuera contra la banda.",
    region: "hombro",
    image: "/exercises/rot_ext.svg",
  },
  {
    id: "elevacion_plano_escapular",
    name: "Elevación en plano de la escápula",
    description: "Carga controlada del manguito.",
    howTo: "Eleve los brazos a 30° de la frontal, pulgar arriba, hasta 90° o el rango indoloro.",
    region: "hombro",
    image: "/exercises/elevacion.svg",
  },
  {
    id: "deslizamiento_mesa",
    name: "Deslizamiento sobre mesa",
    description: "Flexión asistida de hombro rígido.",
    howTo: "Sentado frente a una mesa, deslice un paño hacia delante con la mano afectada.",
    region: "hombro",
    image: "/exercises/mesa.svg",
  },
  {
    id: "extensor_excentrico",
    name: "Extensión de muñeca excéntrica",
    description: "Carga tendinosa para epicondilalgia.",
    howTo: "Antebrazo apoyado, palma abajo. Suba la muñeca con la otra mano y baje solo con la afectada.",
    region: "codo",
    image: "/exercises/extensor.svg",
  },
  {
    id: "prono_supinacion",
    name: "Prono-supinación con palo",
    description: "Movilidad y carga ligera de codo.",
    howTo: "Codo a 90°, gire un palo o martillo en pronación y supinación lenta.",
    region: "codo",
    image: "/exercises/prono.svg",
  },
  {
    id: "agarre_suave",
    name: "Agarre dosificado",
    description: "Carga de flexores y extensores.",
    howTo: "Apriete una pelota blanda 5 s y suelte. Dolor ≤3/10.",
    region: "mano",
    image: "/exercises/agarre.svg",
  },
  {
    id: "deslizamiento_mediano",
    name: "Deslizamiento tendinoso y del mediano",
    description: "Movilidad en túnel carpiano.",
    howTo: "Extienda dedos y muñeca, luego haga puño suave. 8–10 repeticiones sin parestesias intensas.",
    region: "muneca",
    image: "/exercises/mediano.svg",
  },
  {
    id: "movilidad_muneca",
    name: "Movilidad de muñeca",
    description: "Flexoextensión y desviaciones en rango libre.",
    howTo: "Antebrazo apoyado, mueva la muñeca en los cuatro sentidos de forma lenta.",
    region: "muneca",
    image: "/exercises/muneca.svg",
  },
  {
    id: "tendon_gliding",
    name: "Deslizamiento tendinoso de los dedos",
    description: "Gancho, puño recto y puño completo.",
    howTo: "Secuencia: dedos extendidos → gancho → puño recto → puño. 5 ciclos.",
    region: "mano",
    image: "/exercises/tendones.svg",
  },
  {
    id: "sentadilla_asistida",
    name: "Sentadilla asistida",
    description: "Fuerza de cuádriceps y glúteos.",
    howTo: "Frente a una silla, baje como para sentarse y vuelva a subir. Use el respaldo si hace falta.",
    region: "rodilla",
    image: "/exercises/sentadilla.svg",
  },
  {
    id: "extension_rodilla",
    name: "Extensión de rodilla sentado",
    description: "Cuádriceps en cadena abierta dosificada.",
    howTo: "Sentado, extienda la rodilla y baje en 3 s. Añada peso de tobillo si es indoloro.",
    region: "rodilla",
    image: "/exercises/ext_rodilla.svg",
  },
  {
    id: "almeja",
    name: "Almeja (clamshell)",
    description: "Glúteo medio.",
    howTo: "Decúbito lateral, rodillas flexionadas, abra la rodilla de arriba sin rotar la pelvis.",
    region: "cadera",
    image: "/exercises/almeja.svg",
  },
  {
    id: "step_down",
    name: "Bajada de escalón (step-down)",
    description: "Control femoropatelar.",
    howTo: "Desde un escalón bajo, baje el talón libre rozando el suelo y vuelva. Rodilla alineada con el pie.",
    region: "rodilla",
    image: "/exercises/step.svg",
  },
  {
    id: "dorsiflexion",
    name: "Dorsiflexión activa de tobillo",
    description: "Movilidad y tibialis anterior.",
    howTo: "Sentado, lleve la punta del pie hacia la tibia. 15 repeticiones.",
    region: "tobillo",
    image: "/exercises/dorsi.svg",
  },
  {
    id: "equilibrio_unipodal",
    name: "Equilibrio unipodal",
    description: "Estabilidad de tobillo, cadera y prevención de caídas.",
    howTo: "Apoyo en un pie 20–30 s junto a una barra. Progrese a ojos cerrados o superficie inestable.",
    region: "equilibrio",
    image: "/exercises/unipodal.svg",
  },
  {
    id: "abecedario_tobillo",
    name: "Abecedario con el tobillo",
    description: "Movilidad precoz post-esguince.",
    howTo: "Con la punta del pie dibuje las letras del abecedario en el aire.",
    region: "tobillo",
    image: "/exercises/abc.svg",
  },
  {
    id: "estiramiento_fascia",
    name: "Estiramiento de fascia plantar",
    description: "Tensión de fascia y gemelo.",
    howTo: "Sentado, cruce la pierna y estire el hallux hacia la tibia. 3 × 30 s.",
    region: "pie",
    image: "/exercises/fascia.svg",
  },
  {
    id: "elevacion_talon",
    name: "Elevación de talones",
    description: "Carga del tríceps sural y Aquiles.",
    howTo: "De pie, suba los talones y baje en 3 s. Progrese a una pierna.",
    region: "tobillo",
    image: "/exercises/talon.svg",
  },
  {
    id: "elevacion_talon_excentrica",
    name: "Elevación de talón excéntrica",
    description: "Protocolo de carga para tendinopatía aquilea.",
    howTo: "Suba con las dos piernas, baje solo con la afectada en 4 s. 3 × 15.",
    region: "tobillo",
    image: "/exercises/talon_ecc.svg",
  },
  {
    id: "masaje_pelota",
    name: "Rodillo de fascia con pelota",
    description: "Automasaje plantar.",
    howTo: "De pie o sentado, ruede una pelota bajo el arco 2 minutos. Evite dolor agudo.",
    region: "pie",
    image: "/exercises/pelota.svg",
  },
  {
    id: "grandes_amplitudes",
    name: "Movimientos de gran amplitud (LSVT-like)",
    description: "Amplitud de marcha y brazos en Parkinson.",
    howTo: "Zancadas amplias, braceo grande y voz alta en un pasillo despejado.",
    region: "global",
    image: "/exercises/amplitud.svg",
  },
  {
    id: "alcance_ms",
    name: "Alcances de miembro superior",
    description: "Tarea específica post-ACV.",
    howTo: "Sentado, alcance vasos a distintas alturas con el brazo afectado, asistido si hace falta.",
    region: "miembro_superior",
    image: "/exercises/alcance.svg",
  },
  {
    id: "chair_stand_ej",
    name: "Levantarse de la silla",
    description: "Fuerza de miembros inferiores y prevención de caídas.",
    howTo: "De silla a de pie 8–12 repeticiones. Brazos cruzados si es posible.",
    region: "global",
    image: "/exercises/silla.svg",
  },
  {
    id: "brandt_daroff",
    name: "Ejercicios de Brandt-Daroff",
    description: "Habituación / complemento en VPPB.",
    howTo:
      "Desde sedestación, acuéstese de lado con la cabeza a 45° hasta que cese el vértigo; siéntese; repita al otro lado.",
    region: "equilibrio",
    image: "/exercises/brandt.svg",
  },
];

export const EXERCISE_BY_ID = Object.fromEntries(EXERCISES.map((e) => [e.id, e]));
