import type { Region, ResultType, TestCategory } from "../types";

export type CatalogTest = {
  id: string;
  name: string;
  shortName: string;
  category: TestCategory;
  regions: Region[];
  indications: string[];
  description: string;
  howTo: string;
  resultType: ResultType;
  scaleMin?: number;
  scaleMax?: number;
  scaleLabel?: string;
  citationIds: string[];
};

export const TESTS: CatalogTest[] = [
  {
    id: "vas",
    name: "Escala visual analógica de dolor (EVA)",
    shortName: "EVA / VAS",
    category: "musculoesqueletico",
    regions: ["global"],
    indications: ["dolor", "seguimiento"],
    description:
      "Autoevaluación de intensidad del dolor de 0 (sin dolor) a 10 (el peor imaginable).",
    howTo:
      "Pida al paciente que marque o nombre un número de 0 a 10 según el dolor actual, en reposo y en actividad.",
    resultType: "vas",
    scaleMin: 0,
    scaleMax: 10,
    scaleLabel: "Dolor",
    citationIds: ["hjermstad_vas"],
  },
  {
    id: "daniels_global",
    name: "Fuerza muscular (Daniels y Worthingham)",
    shortName: "Daniels 0–5",
    category: "neurologico",
    regions: ["global"],
    indications: ["debilidad", "paresia", "radiculopatia"],
    description:
      "Gradación de 0 (nula) a 5 (normal) de la fuerza de un músculo o grupo.",
    howTo:
      "Evalúe el músculo contra gravedad y resistencia. 0 nula, 1 contracción, 2 sin gravedad, 3 contra gravedad, 4 resistencia incompleta, 5 normal.",
    resultType: "daniels",
    scaleMin: 0,
    scaleMax: 5,
    scaleLabel: "Fuerza",
    citationIds: ["daniels_worthingham"],
  },
  {
    id: "reflejo_bicipital",
    name: "Reflejo bicipital (C5–C6)",
    shortName: "Bicipital",
    category: "neurologico",
    regions: ["cervical", "miembro_superior"],
    indications: ["cervicalgia", "radiculopatia", "debilidad brazo"],
    description: "Reflejo osteotendinoso del bíceps. Escala 0 a 4.",
    howTo:
      "Codo en flexión ligera, percute el tendón bicipital con el pulgar. 0 ausente, 1 hipo, 2 normal, 3 vivo, 4 clonus.",
    resultType: "reflejo",
    scaleMin: 0,
    scaleMax: 4,
    scaleLabel: "Reflejo",
    citationIds: ["campbell_reflexes", "nass_cervical_radic"],
  },
  {
    id: "reflejo_tricipital",
    name: "Reflejo tricipital (C7)",
    shortName: "Tricipital",
    category: "neurologico",
    regions: ["cervical", "miembro_superior"],
    indications: ["cervicalgia", "radiculopatia"],
    description: "Reflejo del tríceps. Escala 0 a 4.",
    howTo: "Brazo relajado, percute el tendón del tríceps proximal al olécranon.",
    resultType: "reflejo",
    scaleMin: 0,
    scaleMax: 4,
    scaleLabel: "Reflejo",
    citationIds: ["campbell_reflexes"],
  },
  {
    id: "reflejo_rotuliano",
    name: "Reflejo rotuliano (L3–L4)",
    shortName: "Rotuliano",
    category: "neurologico",
    regions: ["lumbar", "miembro_inferior"],
    indications: ["lumbalgia", "ciatica", "radiculopatia"],
    description: "Reflejo patelar. Escala 0 a 4.",
    howTo: "Rodilla flexionada, percute el tendón rotuliano.",
    resultType: "reflejo",
    scaleMin: 0,
    scaleMax: 4,
    scaleLabel: "Reflejo",
    citationIds: ["campbell_reflexes", "nass_lumbar_radic"],
  },
  {
    id: "reflejo_aquileo",
    name: "Reflejo aquileo (S1)",
    shortName: "Aquíleo",
    category: "neurologico",
    regions: ["lumbar", "tobillo"],
    indications: ["ciatica", "radiculopatia", "s1"],
    description: "Reflejo del tendón de Aquiles. Escala 0 a 4.",
    howTo: "Pie en ligera dorsiflexión, percute el tendón de Aquiles.",
    resultType: "reflejo",
    scaleMin: 0,
    scaleMax: 4,
    scaleLabel: "Reflejo",
    citationIds: ["campbell_reflexes", "nass_lumbar_radic"],
  },
  {
    id: "babinski",
    name: "Signo de Babinski",
    shortName: "Babinski",
    category: "neurologico",
    regions: ["global"],
    indications: ["mielopatia", "piramidal", "acv"],
    description:
      "Extensión del hallux al estimular el borde lateral de la planta. Sugiere lesión de vía piramidal.",
    howTo:
      "Estimule el borde lateral de la planta hacia el metatarso. Positivo: extensión del primer dedo y apertura en abanico.",
    resultType: "positivo_negativo",
    citationIds: ["campbell_reflexes", "fehlings_2017"],
  },
  {
    id: "clonus",
    name: "Clonus aquileo",
    shortName: "Clonus",
    category: "neurologico",
    regions: ["global", "tobillo"],
    indications: ["espasticidad", "mielopatia"],
    description: "Contracciones rítmicas al dorsiflexionar bruscamente el pie.",
    howTo: "Dorsiflexión rápida y sostenida del pie. Positivo si ≥3 latidos.",
    resultType: "positivo_negativo",
    citationIds: ["campbell_reflexes", "fehlings_2017"],
  },
  {
    id: "romberg",
    name: "Prueba de Romberg",
    shortName: "Romberg",
    category: "neurologico",
    regions: ["equilibrio"],
    indications: ["inestabilidad", "ataxia", "neuropatia"],
    description: "Equilibrio en bipedestación con ojos abiertos y cerrados.",
    howTo:
      "Pies juntos 30 s con ojos abiertos y luego cerrados. Positivo si se desequilibra al cerrar los ojos.",
    resultType: "positivo_negativo",
    citationIds: ["campbell_reflexes"],
  },
  {
    id: "finger_nose",
    name: "Prueba dedo-nariz",
    shortName: "Dedo-nariz",
    category: "neurologico",
    regions: ["global"],
    indications: ["ataxia", "cerebelo", "temblor"],
    description: "Coordinación de miembro superior.",
    howTo:
      "El paciente toca su nariz y luego el dedo del examinador en sucesión. Observe dismetría o temblor intencional.",
    resultType: "positivo_negativo",
    citationIds: ["campbell_reflexes"],
  },
  {
    id: "heel_shin",
    name: "Prueba talón-rodilla",
    shortName: "Talón-rodilla",
    category: "neurologico",
    regions: ["miembro_inferior"],
    indications: ["ataxia", "cerebelo"],
    description: "Coordinación de miembro inferior.",
    howTo:
      "En decúbito, deslizar el talón a lo largo de la tibia contralateral.",
    resultType: "positivo_negativo",
    citationIds: ["campbell_reflexes"],
  },
  {
    id: "lasegue",
    name: "Test de Lasègue (elevación de la pierna recta)",
    shortName: "Lasègue / SLR",
    category: "neurologico",
    regions: ["lumbar", "miembro_inferior"],
    indications: ["ciatica", "lumbalgia", "radiculopatia", "hernia"],
    description:
      "Reproducción de dolor radicular al elevar la pierna extendida, típico de compromiso L5–S1.",
    howTo:
      "Decúbito supino, elevar la pierna con rodilla en extensión. Positivo si dolor irradiado entre 30° y 70°.",
    resultType: "positivo_negativo",
    citationIds: ["nass_lumbar_radic", "nice_ng59"],
  },
  {
    id: "slump",
    name: "Slump test",
    shortName: "Slump",
    category: "neurologico",
    regions: ["lumbar", "cervical"],
    indications: ["ciatica", "radiculopatia", "neuralgia"],
    description: "Sensibilización neural en sedestación.",
    howTo:
      "Sedestación, flexión de tronco y cuello, extensión de rodilla y dorsiflexión. Positivo si reproduce síntomas y se alivia al extender el cuello.",
    resultType: "positivo_negativo",
    citationIds: ["nass_lumbar_radic"],
  },
  {
    id: "spurling",
    name: "Test de Spurling",
    shortName: "Spurling",
    category: "neurologico",
    regions: ["cervical"],
    indications: ["cervicalgia", "radiculopatia", "braquialgia"],
    description: "Compresión foraminal cervical.",
    howTo:
      "Extensión y lateroflexión ipsilateral con compresión axial suave. Positivo si reproduce dolor irradiado al brazo.",
    resultType: "positivo_negativo",
    citationIds: ["nass_cervical_radic", "jospt_neck_2017"],
  },
  {
    id: "distraccion_cervical",
    name: "Test de distracción cervical",
    shortName: "Distracción",
    category: "neurologico",
    regions: ["cervical"],
    indications: ["cervicalgia", "radiculopatia"],
    description: "Alivio de síntomas radiculares al traccionar el cuello.",
    howTo: "Tracción axial suave en sedestación o decúbito. Positivo si disminuye el dolor irradiado.",
    resultType: "positivo_negativo",
    citationIds: ["jospt_neck_2017"],
  },
  {
    id: "ulnt1",
    name: "Test neurodinámico del nervio mediano (ULNT1)",
    shortName: "ULNT1",
    category: "neurologico",
    regions: ["cervical", "miembro_superior"],
    indications: ["cervicalgia", "tunel_carpiano", "braquialgia"],
    description: "Movilización del nervio mediano.",
    howTo:
      "Depresión escapular, abducción, supinación, extensión de muñeca y codo. Positivo si reproduce síntomas y se sensibiliza con lateroflexión cervical.",
    resultType: "positivo_negativo",
    citationIds: ["jospt_neck_2017"],
  },
  {
    id: "hawkins",
    name: "Test de Hawkins-Kennedy",
    shortName: "Hawkins",
    category: "musculoesqueletico",
    regions: ["hombro"],
    indications: ["hombro", "manguito", "impingement"],
    description: "Conflicto subacromial.",
    howTo:
      "Hombro y codo a 90°, rotación interna pasiva. Positivo si dolor en cara anterior o lateral.",
    resultType: "positivo_negativo",
    citationIds: ["aaos_rc", "kuhn_2009"],
  },
  {
    id: "neer",
    name: "Test de Neer",
    shortName: "Neer",
    category: "musculoesqueletico",
    regions: ["hombro"],
    indications: ["hombro", "manguito"],
    description: "Elevación pasiva en rotación interna.",
    howTo: "Estabilice la escápula y eleve el brazo en flexión con rotación interna.",
    resultType: "positivo_negativo",
    citationIds: ["aaos_rc"],
  },
  {
    id: "jobe",
    name: "Test de Jobe (empty can)",
    shortName: "Jobe",
    category: "musculoesqueletico",
    regions: ["hombro"],
    indications: ["hombro", "supraespinoso"],
    description: "Integridad del supraespinoso.",
    howTo:
      "Abducción 90° en plano de la escápula, pulgar hacia abajo, resistencia a la elevación.",
    resultType: "daniels",
    scaleMin: 0,
    scaleMax: 5,
    scaleLabel: "Fuerza supraespinoso",
    citationIds: ["aaos_rc", "daniels_worthingham"],
  },
  {
    id: "speed",
    name: "Test de Speed",
    shortName: "Speed",
    category: "musculoesqueletico",
    regions: ["hombro"],
    indications: ["biceps", "hombro"],
    description: "Tendón de la porción larga del bíceps.",
    howTo: "Codo extendido, antebrazo en supinación, resistencia a la flexión del hombro.",
    resultType: "positivo_negativo",
    citationIds: ["aaos_rc"],
  },
  {
    id: "drop_arm",
    name: "Drop arm test",
    shortName: "Drop arm",
    category: "musculoesqueletico",
    regions: ["hombro"],
    indications: ["rotura manguito"],
    description: "Incapacidad de descender el brazo de forma controlada.",
    howTo: "Abducción pasiva a 90° y pedir descenso lento. Positivo si el brazo cae.",
    resultType: "positivo_negativo",
    citationIds: ["aaos_rc"],
  },
  {
    id: "capsulitis_rom",
    name: "Arco de movimiento pasivo de hombro",
    shortName: "ROM hombro",
    category: "musculoesqueletico",
    regions: ["hombro"],
    indications: ["hombro congelado", "capsulitis", "rigidez"],
    description: "Medición goniométrica de flexión, abducción y rotaciones.",
    howTo: "Mida grados de flexión, abducción, rotación externa e interna pasivas.",
    resultType: "rom",
    scaleMin: 0,
    scaleMax: 180,
    scaleLabel: "Grados",
    citationIds: ["jospt_shoulder_2020"],
  },
  {
    id: "cozen",
    name: "Test de Cozen",
    shortName: "Cozen",
    category: "musculoesqueletico",
    regions: ["codo"],
    indications: ["epicondilitis", "codo"],
    description: "Epicondilalgia lateral.",
    howTo:
      "Codo flexionado, puño cerrado, extensión y desviación radial de muñeca contra resistencia. Dolor en epicóndilo.",
    resultType: "positivo_negativo",
    citationIds: ["coombes_2015"],
  },
  {
    id: "mills",
    name: "Test de Mill",
    shortName: "Mill",
    category: "musculoesqueletico",
    regions: ["codo"],
    indications: ["epicondilitis"],
    description: "Estiramiento de extensores de muñeca.",
    howTo: "Extensión de codo, pronación y flexión palmar. Positivo si dolor en epicóndilo.",
    resultType: "positivo_negativo",
    citationIds: ["coombes_2015"],
  },
  {
    id: "phalen",
    name: "Test de Phalen",
    shortName: "Phalen",
    category: "neurologico",
    regions: ["muneca", "mano"],
    indications: ["tunel carpiano", "hormigueo mano"],
    description: "Compresión del nervio mediano en el túnel carpiano.",
    howTo: "Flexión palmar máxima de ambas muñecas 60 s. Positivo si parestesias en territorio mediano.",
    resultType: "positivo_negativo",
    citationIds: ["padua_2016"],
  },
  {
    id: "tinel_carpiano",
    name: "Signo de Tinel (muñeca)",
    shortName: "Tinel",
    category: "neurologico",
    regions: ["muneca"],
    indications: ["tunel carpiano"],
    description: "Percusión del nervio mediano.",
    howTo: "Percuta el retináculo flexor. Positivo si hormigueo distal en mediano.",
    resultType: "positivo_negativo",
    citationIds: ["padua_2016"],
  },
  {
    id: "mcmurray",
    name: "Test de McMurray",
    shortName: "McMurray",
    category: "musculoesqueletico",
    regions: ["rodilla"],
    indications: ["menisco", "rodilla"],
    description: "Provoca dolor o chasquido meniscal.",
    howTo:
      "Flexión máxima, rotación tibial y extensión. Medial: rotación externa; lateral: rotación interna.",
    resultType: "positivo_negativo",
    citationIds: ["oarsi_2019"],
  },
  {
    id: "lachman",
    name: "Test de Lachman",
    shortName: "Lachman",
    category: "musculoesqueletico",
    regions: ["rodilla"],
    indications: ["lca", "inestabilidad rodilla"],
    description: "Traslado anterior de la tibia a 20–30° de flexión.",
    howTo: "Estabilice el fémur, traduzca la tibia hacia delante. Positivo si cajón blando.",
    resultType: "positivo_negativo",
    citationIds: ["oarsi_2019"],
  },
  {
    id: "cajon_anterior",
    name: "Cajón anterior de rodilla",
    shortName: "Cajón anterior",
    category: "musculoesqueletico",
    regions: ["rodilla"],
    indications: ["lca"],
    description: "Traslado anterior a 90° de flexión.",
    howTo: "Sentado sobre el pie, traduzca la tibia. Compare con el lado sano.",
    resultType: "positivo_negativo",
    citationIds: ["oarsi_2019"],
  },
  {
    id: "valgo_rodilla",
    name: "Estrés en valgo (ligamento colateral medial)",
    shortName: "Valgo",
    category: "musculoesqueletico",
    regions: ["rodilla"],
    indications: ["lcm", "esguince rodilla"],
    description: "Integridad del LCM a 0° y 30°.",
    howTo: "Fuerza en valgo con rodilla a 30°. Positivo si dolor o apertura medial.",
    resultType: "positivo_negativo",
    citationIds: ["oarsi_2019"],
  },
  {
    id: "clarke",
    name: "Test de Clarke / compresión femoropatelar",
    shortName: "Clarke",
    category: "musculoesqueletico",
    regions: ["rodilla"],
    indications: ["femoropatelar", "rodilla anterior"],
    description: "Dolor al contraer el cuádriceps con presión sobre la rótula.",
    howTo: "Presione suavemente la rótula hacia distal y pida contracción del cuádriceps.",
    resultType: "positivo_negativo",
    citationIds: ["jospt_pfps"],
  },
  {
    id: "faber",
    name: "Test de FABER (Patrick)",
    shortName: "FABER",
    category: "musculoesqueletico",
    regions: ["cadera", "lumbar"],
    indications: ["cadera", "sacroiliaca", "coxartrosis"],
    description: "Flexión, abducción y rotación externa de cadera.",
    howTo:
      "Tobillo sobre la rodilla contralateral y presión sobre la rodilla flexionada. Dolor inguinal sugiere cadera; posterior, sacroilíaca.",
    resultType: "positivo_negativo",
    citationIds: ["jospt_hip_oa"],
  },
  {
    id: "fadir",
    name: "Test de FADIR",
    shortName: "FADIR",
    category: "musculoesqueletico",
    regions: ["cadera"],
    indications: ["choque femoroacetabular", "cadera"],
    description: "Flexión, aducción y rotación interna.",
    howTo: "Cadera a 90°, aducción y rotación interna. Positivo si dolor inguinal.",
    resultType: "positivo_negativo",
    citationIds: ["jospt_hip_oa"],
  },
  {
    id: "trendelenburg",
    name: "Signo de Trendelenburg",
    shortName: "Trendelenburg",
    category: "musculoesqueletico",
    regions: ["cadera"],
    indications: ["gluteo medio", "coxartrosis"],
    description: "Descenso de la pelvis contralateral en apoyo unipodal.",
    howTo: "Apoyo unipodal 30 s. Positivo si la pelvis cae del lado libre.",
    resultType: "positivo_negativo",
    citationIds: ["jospt_hip_oa", "daniels_worthingham"],
  },
  {
    id: "thomas",
    name: "Test de Thomas",
    shortName: "Thomas",
    category: "musculoesqueletico",
    regions: ["cadera"],
    indications: ["psoas", "flexo de cadera"],
    description: "Acortamiento de flexores de cadera.",
    howTo: "El paciente abraza una rodilla al pecho. Observe si el muslo contralateral se eleva.",
    resultType: "positivo_negativo",
    citationIds: ["jospt_hip_oa"],
  },
  {
    id: "ober",
    name: "Test de Ober",
    shortName: "Ober",
    category: "musculoesqueletico",
    regions: ["cadera"],
    indications: ["cintilla ili Tibial", "tfl"],
    description: "Tensión de la banda iliotibial.",
    howTo: "Decúbito lateral, abducción y extensión de cadera; soltar. Positivo si la pierna no desciende.",
    resultType: "positivo_negativo",
    citationIds: ["jospt_pfps"],
  },
  {
    id: "schober",
    name: "Test de Schober modificado",
    shortName: "Schober",
    category: "musculoesqueletico",
    regions: ["lumbar"],
    indications: ["espondiloartritis", "rigidez lumbar"],
    description: "Movilidad lumbar en flexión.",
    howTo:
      "Marque 5 cm bajo y 10 cm sobre L5. Flexión máxima. Positivo si el aumento es <5 cm.",
    resultType: "rom",
    scaleMin: 0,
    scaleMax: 10,
    scaleLabel: "cm de incremento",
    citationIds: ["nice_ng65"],
  },
  {
    id: "thompson",
    name: "Test de Thompson",
    shortName: "Thompson",
    category: "musculoesqueletico",
    regions: ["tobillo"],
    indications: ["aquiles", "rotura"],
    description: "Integridad del tendón de Aquiles.",
    howTo: "Decúbito prono, comprima los gemelos. Positivo (rotura) si no hay flexión plantar.",
    resultType: "positivo_negativo",
    citationIds: ["jospt_achilles"],
  },
  {
    id: "ottawa_tobillo",
    name: "Reglas de Ottawa para tobillo",
    shortName: "Ottawa",
    category: "musculoesqueletico",
    regions: ["tobillo", "pie"],
    indications: ["esguince", "trauma tobillo", "fractura"],
    description:
      "Criterios para indicar radiografía tras traumatismo de tobillo o mediopié.",
    howTo:
      "Dolor en maléolo y dolor a la palpación ósea o incapacidad de apoyar cuatro pasos. Positivo: derivar a imagen.",
    resultType: "positivo_negativo",
    citationIds: ["downs_ottawa", "vuurberg_2018"],
  },
  {
    id: "cajon_anterior_tobillo",
    name: "Cajón anterior de tobillo",
    shortName: "Cajón tobillo",
    category: "musculoesqueletico",
    regions: ["tobillo"],
    indications: ["lpea", "esguince"],
    description: "Integridad del ligamento peroneoastragalino anterior.",
    howTo: "Talón estable, traduzca el astrágalo hacia delante en 10–20° de plantarflexión.",
    resultType: "positivo_negativo",
    citationIds: ["vuurberg_2018"],
  },
  {
    id: "windlass",
    name: "Test de Windlass",
    shortName: "Windlass",
    category: "musculoesqueletico",
    regions: ["pie"],
    indications: ["fascitis", "talon"],
    description: "Tensión de la fascia plantar al extender el hallux.",
    howTo: "En carga o descarga, extensión del primer dedo. Positivo si dolor en inserción calcánea.",
    resultType: "positivo_negativo",
    citationIds: ["jospt_plantar"],
  },
  {
    id: "dix_hallpike",
    name: "Maniobra de Dix-Hallpike",
    shortName: "Dix-Hallpike",
    category: "neurologico",
    regions: ["equilibrio", "cervical"],
    indications: ["vertigo", "vppb"],
    description: "Diagnóstico de VPPB del canal posterior.",
    howTo:
      "Desde sedestación, giro 45° y decúbito rápido con 20° de extensión. Positivo: nistagmo y vértigo transitorio.",
    resultType: "positivo_negativo",
    citationIds: ["bhattacharyya_2017"],
  },
  {
    id: "berg",
    name: "Escala de equilibrio de Berg",
    shortName: "Berg",
    category: "adulto_mayor",
    regions: ["equilibrio", "global"],
    indications: ["caidas", "adulto mayor", "equilibrio"],
    description: "14 ítems, 0 a 56. Riesgo de caída si <45.",
    howTo: "Administre las 14 tareas (sentado a de pie, giros, unipodal, etc.) y sume el puntaje.",
    resultType: "escala",
    scaleMin: 0,
    scaleMax: 56,
    scaleLabel: "Puntaje Berg",
    citationIds: ["berg_1989", "ags_bgs_falls"],
  },
  {
    id: "tug",
    name: "Timed Up and Go",
    shortName: "TUG",
    category: "adulto_mayor",
    regions: ["equilibrio", "global"],
    indications: ["caidas", "movilidad", "parkinson", "acv"],
    description: "Tiempo para levantarse, caminar 3 m, volver y sentarse.",
    howTo: "Silla sin reposabrazos, 3 metros. Cronometre. ≥12–14 s sugiere riesgo de caída.",
    resultType: "tiempo",
    scaleMin: 0,
    scaleMax: 60,
    scaleLabel: "Segundos",
    citationIds: ["podsiadlo_tug", "nice_cg161"],
  },
  {
    id: "tinetti",
    name: "Escala de Tinetti (POMA)",
    shortName: "Tinetti",
    category: "adulto_mayor",
    regions: ["equilibrio", "global"],
    indications: ["caidas", "marcha"],
    description: "Equilibrio y marcha, 0 a 28.",
    howTo: "Evalúe equilibrio sentado/de pie y los ítems de marcha. <19 alto riesgo de caída.",
    resultType: "escala",
    scaleMin: 0,
    scaleMax: 28,
    scaleLabel: "Puntaje Tinetti",
    citationIds: ["tinetti_1986", "ags_bgs_falls"],
  },
  {
    id: "sppb",
    name: "Short Physical Performance Battery",
    shortName: "SPPB",
    category: "adulto_mayor",
    regions: ["global"],
    indications: ["fragilidad", "adulto mayor"],
    description: "Equilibrio, marcha 4 m y levantarse 5 veces. 0 a 12.",
    howTo: "Sume los tres subtests (0–4 cada uno). ≤9 sugiere limitación funcional.",
    resultType: "escala",
    scaleMin: 0,
    scaleMax: 12,
    scaleLabel: "Puntaje SPPB",
    citationIds: ["guralnik_sppb"],
  },
  {
    id: "barthel",
    name: "Índice de Barthel",
    shortName: "Barthel",
    category: "adulto_mayor",
    regions: ["global"],
    indications: ["acv", "dependencia", "adulto mayor"],
    description: "Independencia en actividades básicas, 0 a 100.",
    howTo: "Puntúe alimentación, baño, vestido, continencia, traslado y marcha.",
    resultType: "escala",
    scaleMin: 0,
    scaleMax: 100,
    scaleLabel: "Barthel",
    citationIds: ["mahoney_barthel", "aha_stroke_2016"],
  },
  {
    id: "chair_stand",
    name: "Levantarse de la silla en 30 segundos",
    shortName: "Chair stand 30 s",
    category: "adulto_mayor",
    regions: ["miembro_inferior"],
    indications: ["fuerza", "caidas", "sarcopenia"],
    description: "Número de repeticiones en 30 s.",
    howTo: "Brazos cruzados al pecho, cuente las repeticiones completas en 30 s.",
    resultType: "escala",
    scaleMin: 0,
    scaleMax: 30,
    scaleLabel: "Repeticiones",
    citationIds: ["guralnik_sppb", "ags_bgs_falls"],
  },
  {
    id: "grip",
    name: "Fuerza de prensión (dinamometría)",
    shortName: "Prensión",
    category: "adulto_mayor",
    regions: ["mano"],
    indications: ["sarcopenia", "fragilidad"],
    description: "Kilogramos de prensión. Punto de corte habitual: <27 kg hombres, <16 kg mujeres.",
    howTo: "Brazo al lado del cuerpo, codo a 90° si se usa protocolo Jamar. Mejor de tres intentos.",
    resultType: "escala",
    scaleMin: 0,
    scaleMax: 80,
    scaleLabel: "kg",
    citationIds: ["guralnik_sppb"],
  },
  {
    id: "updrs_marcha",
    name: "Marcha y equilibrio en Parkinson (ítem clínico)",
    shortName: "Marcha Parkinson",
    category: "neurologico",
    regions: ["equilibrio"],
    indications: ["parkinson", "festination", "freezing"],
    description: "Observación de velocidad, braceo, freezing y giros.",
    howTo: "Observe 10 m de marcha, giro de 180° y dual task. Anote freezing o festinación.",
    resultType: "texto",
    citationIds: ["nice_ng71", "keus_kngf"],
  },
  {
    id: "sensibilidad",
    name: "Sensibilidad táctil y algésica por dermatoma",
    shortName: "Sensibilidad",
    category: "neurologico",
    regions: ["global"],
    indications: ["radiculopatia", "neuropatia", "mielopatia"],
    description: "Mapa de hipoestesia o disestesia.",
    howTo: "Compare tacto suave y pinchazo por dermatoma y hemicuerpo. Anote el territorio.",
    resultType: "texto",
    citationIds: ["campbell_reflexes", "popbusui_2017"],
  },
  {
    id: "monofilamento",
    name: "Monofilamento de 10 g (Semmes-Weinstein)",
    shortName: "Monofilamento",
    category: "neurologico",
    regions: ["pie"],
    indications: ["diabetes", "neuropatia"],
    description: "Pérdida de sensibilidad protectora plantar.",
    howTo: "Aplique el monofilamento en puntos plantares hasta que se doble. Positivo: no percibe.",
    resultType: "positivo_negativo",
    citationIds: ["popbusui_2017"],
  },
];

export const TEST_BY_ID = Object.fromEntries(TESTS.map((t) => [t.id, t]));
